// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3BoxCastInput {
 *     b3AABB box;
 *     b3Vec3 translation;
 *     float maxFraction;
 * }
 * }
 */
public class b3BoxCastInput {

    b3BoxCastInput() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3AABB.layout().withName("box"),
        b3Vec3.layout().withName("translation"),
        Box3D.C_FLOAT.withName("maxFraction")
    ).withName("b3BoxCastInput");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout box$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("box"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3AABB box
     * }
     */
    public static final GroupLayout box$layout() {
        return box$LAYOUT;
    }

    private static final long box$OFFSET = $LAYOUT.byteOffset(groupElement("box"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3AABB box
     * }
     */
    public static final long box$offset() {
        return box$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3AABB box
     * }
     */
    public static MemorySegment box(MemorySegment struct) {
        return struct.asSlice(box$OFFSET, box$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3AABB box
     * }
     */
    public static void box(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, box$OFFSET, box$LAYOUT.byteSize());
    }

    private static final GroupLayout translation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("translation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final GroupLayout translation$layout() {
        return translation$LAYOUT;
    }

    private static final long translation$OFFSET = $LAYOUT.byteOffset(groupElement("translation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final long translation$offset() {
        return translation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static MemorySegment translation(MemorySegment struct) {
        return struct.asSlice(translation$OFFSET, translation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static void translation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, translation$OFFSET, translation$LAYOUT.byteSize());
    }

    private static final OfFloat maxFraction$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxFraction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final OfFloat maxFraction$layout() {
        return maxFraction$LAYOUT;
    }

    private static final long maxFraction$OFFSET = $LAYOUT.byteOffset(groupElement("maxFraction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final long maxFraction$offset() {
        return maxFraction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static float maxFraction(MemorySegment struct) {
        return struct.get(maxFraction$LAYOUT, maxFraction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static void maxFraction(MemorySegment struct, float fieldValue) {
        struct.set(maxFraction$LAYOUT, maxFraction$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

