// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3Capacity {
 *     int staticShapeCount;
 *     int dynamicShapeCount;
 *     int staticBodyCount;
 *     int dynamicBodyCount;
 *     int contactCount;
 * }
 * }
 */
public class b3Capacity {

    b3Capacity() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_INT.withName("staticShapeCount"),
        Box3D.C_INT.withName("dynamicShapeCount"),
        Box3D.C_INT.withName("staticBodyCount"),
        Box3D.C_INT.withName("dynamicBodyCount"),
        Box3D.C_INT.withName("contactCount")
    ).withName("b3Capacity");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt staticShapeCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("staticShapeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int staticShapeCount
     * }
     */
    public static final OfInt staticShapeCount$layout() {
        return staticShapeCount$LAYOUT;
    }

    private static final long staticShapeCount$OFFSET = $LAYOUT.byteOffset(groupElement("staticShapeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int staticShapeCount
     * }
     */
    public static final long staticShapeCount$offset() {
        return staticShapeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int staticShapeCount
     * }
     */
    public static int staticShapeCount(MemorySegment struct) {
        return struct.get(staticShapeCount$LAYOUT, staticShapeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int staticShapeCount
     * }
     */
    public static void staticShapeCount(MemorySegment struct, int fieldValue) {
        struct.set(staticShapeCount$LAYOUT, staticShapeCount$OFFSET, fieldValue);
    }

    private static final OfInt dynamicShapeCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dynamicShapeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dynamicShapeCount
     * }
     */
    public static final OfInt dynamicShapeCount$layout() {
        return dynamicShapeCount$LAYOUT;
    }

    private static final long dynamicShapeCount$OFFSET = $LAYOUT.byteOffset(groupElement("dynamicShapeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dynamicShapeCount
     * }
     */
    public static final long dynamicShapeCount$offset() {
        return dynamicShapeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dynamicShapeCount
     * }
     */
    public static int dynamicShapeCount(MemorySegment struct) {
        return struct.get(dynamicShapeCount$LAYOUT, dynamicShapeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dynamicShapeCount
     * }
     */
    public static void dynamicShapeCount(MemorySegment struct, int fieldValue) {
        struct.set(dynamicShapeCount$LAYOUT, dynamicShapeCount$OFFSET, fieldValue);
    }

    private static final OfInt staticBodyCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("staticBodyCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int staticBodyCount
     * }
     */
    public static final OfInt staticBodyCount$layout() {
        return staticBodyCount$LAYOUT;
    }

    private static final long staticBodyCount$OFFSET = $LAYOUT.byteOffset(groupElement("staticBodyCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int staticBodyCount
     * }
     */
    public static final long staticBodyCount$offset() {
        return staticBodyCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int staticBodyCount
     * }
     */
    public static int staticBodyCount(MemorySegment struct) {
        return struct.get(staticBodyCount$LAYOUT, staticBodyCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int staticBodyCount
     * }
     */
    public static void staticBodyCount(MemorySegment struct, int fieldValue) {
        struct.set(staticBodyCount$LAYOUT, staticBodyCount$OFFSET, fieldValue);
    }

    private static final OfInt dynamicBodyCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dynamicBodyCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dynamicBodyCount
     * }
     */
    public static final OfInt dynamicBodyCount$layout() {
        return dynamicBodyCount$LAYOUT;
    }

    private static final long dynamicBodyCount$OFFSET = $LAYOUT.byteOffset(groupElement("dynamicBodyCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dynamicBodyCount
     * }
     */
    public static final long dynamicBodyCount$offset() {
        return dynamicBodyCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dynamicBodyCount
     * }
     */
    public static int dynamicBodyCount(MemorySegment struct) {
        return struct.get(dynamicBodyCount$LAYOUT, dynamicBodyCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dynamicBodyCount
     * }
     */
    public static void dynamicBodyCount(MemorySegment struct, int fieldValue) {
        struct.set(dynamicBodyCount$LAYOUT, dynamicBodyCount$OFFSET, fieldValue);
    }

    private static final OfInt contactCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("contactCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final OfInt contactCount$layout() {
        return contactCount$LAYOUT;
    }

    private static final long contactCount$OFFSET = $LAYOUT.byteOffset(groupElement("contactCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final long contactCount$offset() {
        return contactCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static int contactCount(MemorySegment struct) {
        return struct.get(contactCount$LAYOUT, contactCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static void contactCount(MemorySegment struct, int fieldValue) {
        struct.set(contactCount$LAYOUT, contactCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

