// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3Capsule {
 *     b3Vec3 center1;
 *     b3Vec3 center2;
 *     float radius;
 * }
 * }
 */
public class b3Capsule {

    b3Capsule() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Vec3.layout().withName("center1"),
        b3Vec3.layout().withName("center2"),
        Box3D.C_FLOAT.withName("radius")
    ).withName("b3Capsule");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout center1$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("center1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 center1
     * }
     */
    public static final GroupLayout center1$layout() {
        return center1$LAYOUT;
    }

    private static final long center1$OFFSET = $LAYOUT.byteOffset(groupElement("center1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 center1
     * }
     */
    public static final long center1$offset() {
        return center1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 center1
     * }
     */
    public static MemorySegment center1(MemorySegment struct) {
        return struct.asSlice(center1$OFFSET, center1$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 center1
     * }
     */
    public static void center1(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, center1$OFFSET, center1$LAYOUT.byteSize());
    }

    private static final GroupLayout center2$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("center2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 center2
     * }
     */
    public static final GroupLayout center2$layout() {
        return center2$LAYOUT;
    }

    private static final long center2$OFFSET = $LAYOUT.byteOffset(groupElement("center2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 center2
     * }
     */
    public static final long center2$offset() {
        return center2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 center2
     * }
     */
    public static MemorySegment center2(MemorySegment struct) {
        return struct.asSlice(center2$OFFSET, center2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 center2
     * }
     */
    public static void center2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, center2$OFFSET, center2$LAYOUT.byteSize());
    }

    private static final OfFloat radius$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("radius"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static final OfFloat radius$layout() {
        return radius$LAYOUT;
    }

    private static final long radius$OFFSET = $LAYOUT.byteOffset(groupElement("radius"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static final long radius$offset() {
        return radius$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static float radius(MemorySegment struct) {
        return struct.get(radius$LAYOUT, radius$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static void radius(MemorySegment struct, float fieldValue) {
        struct.set(radius$LAYOUT, radius$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

