// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef float (b3CastResultFcn)(b3ShapeId, b3Pos, b3Vec3, float, uint64_t, int, int, void *)
 * }
 */
public final class b3CastResultFcn {

    private b3CastResultFcn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(MemorySegment shapeId, MemorySegment point, MemorySegment normal, float fraction, long userMaterialId, int triangleIndex, int childIndex, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box3D.C_FLOAT,
        b3ShapeId.layout(),
        b3Vec3.layout(),
        b3Vec3.layout(),
        Box3D.C_FLOAT,
        Box3D.C_LONG_LONG,
        Box3D.C_INT,
        Box3D.C_INT,
        Box3D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box3D.upcallHandle(b3CastResultFcn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(b3CastResultFcn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr, MemorySegment shapeId, MemorySegment point, MemorySegment normal, float fraction, long userMaterialId, int triangleIndex, int childIndex, MemorySegment context) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, shapeId, point, normal, fraction, userMaterialId, triangleIndex, childIndex, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

