// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3ChildShape {
 *     union {
 *         b3Capsule capsule;
 *         const b3HullData *hull;
 *         b3Mesh mesh;
 *         b3Sphere sphere;
 *     };
 *     b3Transform transform;
 *     int materialIndices[4];
 *     b3ShapeType type;
 * }
 * }
 */
public class b3ChildShape {

    b3ChildShape() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.unionLayout(
            b3Capsule.layout().withName("capsule"),
            Box3D.C_POINTER.withName("hull"),
            b3Mesh.layout().withName("mesh"),
            b3Sphere.layout().withName("sphere"),
            MemoryLayout.paddingLayout(32)
        ).withName("$anon$2581:2"),
        b3Transform.layout().withName("transform"),
        MemoryLayout.sequenceLayout(4, Box3D.C_INT).withName("materialIndices"),
        Box3D.C_INT.withName("type")
    ).withName("b3ChildShape");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout capsule$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$2581:2"), groupElement("capsule"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static final GroupLayout capsule$layout() {
        return capsule$LAYOUT;
    }

    private static final long capsule$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$2581:2"), groupElement("capsule"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static final long capsule$offset() {
        return capsule$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static MemorySegment capsule(MemorySegment struct) {
        return struct.asSlice(capsule$OFFSET, capsule$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static void capsule(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, capsule$OFFSET, capsule$LAYOUT.byteSize());
    }

    private static final AddressLayout hull$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("$anon$2581:2"), groupElement("hull"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const b3HullData *hull
     * }
     */
    public static final AddressLayout hull$layout() {
        return hull$LAYOUT;
    }

    private static final long hull$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$2581:2"), groupElement("hull"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const b3HullData *hull
     * }
     */
    public static final long hull$offset() {
        return hull$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const b3HullData *hull
     * }
     */
    public static MemorySegment hull(MemorySegment struct) {
        return struct.get(hull$LAYOUT, hull$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const b3HullData *hull
     * }
     */
    public static void hull(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hull$LAYOUT, hull$OFFSET, fieldValue);
    }

    private static final GroupLayout mesh$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$2581:2"), groupElement("mesh"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Mesh mesh
     * }
     */
    public static final GroupLayout mesh$layout() {
        return mesh$LAYOUT;
    }

    private static final long mesh$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$2581:2"), groupElement("mesh"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Mesh mesh
     * }
     */
    public static final long mesh$offset() {
        return mesh$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Mesh mesh
     * }
     */
    public static MemorySegment mesh(MemorySegment struct) {
        return struct.asSlice(mesh$OFFSET, mesh$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Mesh mesh
     * }
     */
    public static void mesh(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, mesh$OFFSET, mesh$LAYOUT.byteSize());
    }

    private static final GroupLayout sphere$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$2581:2"), groupElement("sphere"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static final GroupLayout sphere$layout() {
        return sphere$LAYOUT;
    }

    private static final long sphere$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$2581:2"), groupElement("sphere"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static final long sphere$offset() {
        return sphere$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static MemorySegment sphere(MemorySegment struct) {
        return struct.asSlice(sphere$OFFSET, sphere$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static void sphere(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sphere$OFFSET, sphere$LAYOUT.byteSize());
    }

    private static final GroupLayout transform$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transform"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final GroupLayout transform$layout() {
        return transform$LAYOUT;
    }

    private static final long transform$OFFSET = $LAYOUT.byteOffset(groupElement("transform"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final long transform$offset() {
        return transform$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static MemorySegment transform(MemorySegment struct) {
        return struct.asSlice(transform$OFFSET, transform$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static void transform(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transform$OFFSET, transform$LAYOUT.byteSize());
    }

    private static final SequenceLayout materialIndices$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("materialIndices"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static final SequenceLayout materialIndices$layout() {
        return materialIndices$LAYOUT;
    }

    private static final long materialIndices$OFFSET = $LAYOUT.byteOffset(groupElement("materialIndices"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static final long materialIndices$offset() {
        return materialIndices$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static MemorySegment materialIndices(MemorySegment struct) {
        return struct.asSlice(materialIndices$OFFSET, materialIndices$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static void materialIndices(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, materialIndices$OFFSET, materialIndices$LAYOUT.byteSize());
    }

    private static long[] materialIndices$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static long[] materialIndices$dimensions() {
        return materialIndices$DIMS;
    }
    private static final VarHandle materialIndices$ELEM_HANDLE = materialIndices$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static int materialIndices(MemorySegment struct, long index0) {
        return (int)materialIndices$ELEM_HANDLE.get(struct, materialIndices$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int materialIndices[4]
     * }
     */
    public static void materialIndices(MemorySegment struct, long index0, int fieldValue) {
        materialIndices$ELEM_HANDLE.set(struct, materialIndices$OFFSET, index0, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

