// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3CompoundSphereDef {
 *     b3Sphere sphere;
 *     b3SurfaceMaterial material;
 * }
 * }
 */
public class b3CompoundSphereDef {

    b3CompoundSphereDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Sphere.layout().withName("sphere"),
        b3SurfaceMaterial.layout().withName("material")
    ).withName("b3CompoundSphereDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout sphere$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sphere"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static final GroupLayout sphere$layout() {
        return sphere$LAYOUT;
    }

    private static final long sphere$OFFSET = $LAYOUT.byteOffset(groupElement("sphere"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static final long sphere$offset() {
        return sphere$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static MemorySegment sphere(MemorySegment struct) {
        return struct.asSlice(sphere$OFFSET, sphere$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Sphere sphere
     * }
     */
    public static void sphere(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sphere$OFFSET, sphere$LAYOUT.byteSize());
    }

    private static final GroupLayout material$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("material"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial material
     * }
     */
    public static final GroupLayout material$layout() {
        return material$LAYOUT;
    }

    private static final long material$OFFSET = $LAYOUT.byteOffset(groupElement("material"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial material
     * }
     */
    public static final long material$offset() {
        return material$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial material
     * }
     */
    public static MemorySegment material(MemorySegment struct) {
        return struct.asSlice(material$OFFSET, material$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial material
     * }
     */
    public static void material(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, material$OFFSET, material$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

