// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3Counters {
 *     int bodyCount;
 *     int shapeCount;
 *     int contactCount;
 *     int jointCount;
 *     int islandCount;
 *     int stackUsed;
 *     int arenaCapacity;
 *     int staticTreeHeight;
 *     int treeHeight;
 *     int satCallCount;
 *     int satCacheHitCount;
 *     int byteCount;
 *     int taskCount;
 *     int colorCounts[24];
 *     int manifoldCounts[8];
 *     int awakeContactCount;
 *     int recycledContactCount;
 *     int distanceIterations;
 *     int pushBackIterations;
 *     int rootIterations;
 * }
 * }
 */
public class b3Counters {

    b3Counters() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_INT.withName("bodyCount"),
        Box3D.C_INT.withName("shapeCount"),
        Box3D.C_INT.withName("contactCount"),
        Box3D.C_INT.withName("jointCount"),
        Box3D.C_INT.withName("islandCount"),
        Box3D.C_INT.withName("stackUsed"),
        Box3D.C_INT.withName("arenaCapacity"),
        Box3D.C_INT.withName("staticTreeHeight"),
        Box3D.C_INT.withName("treeHeight"),
        Box3D.C_INT.withName("satCallCount"),
        Box3D.C_INT.withName("satCacheHitCount"),
        Box3D.C_INT.withName("byteCount"),
        Box3D.C_INT.withName("taskCount"),
        MemoryLayout.sequenceLayout(24, Box3D.C_INT).withName("colorCounts"),
        MemoryLayout.sequenceLayout(8, Box3D.C_INT).withName("manifoldCounts"),
        Box3D.C_INT.withName("awakeContactCount"),
        Box3D.C_INT.withName("recycledContactCount"),
        Box3D.C_INT.withName("distanceIterations"),
        Box3D.C_INT.withName("pushBackIterations"),
        Box3D.C_INT.withName("rootIterations")
    ).withName("b3Counters");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt bodyCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bodyCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static final OfInt bodyCount$layout() {
        return bodyCount$LAYOUT;
    }

    private static final long bodyCount$OFFSET = $LAYOUT.byteOffset(groupElement("bodyCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static final long bodyCount$offset() {
        return bodyCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static int bodyCount(MemorySegment struct) {
        return struct.get(bodyCount$LAYOUT, bodyCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static void bodyCount(MemorySegment struct, int fieldValue) {
        struct.set(bodyCount$LAYOUT, bodyCount$OFFSET, fieldValue);
    }

    private static final OfInt shapeCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shapeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static final OfInt shapeCount$layout() {
        return shapeCount$LAYOUT;
    }

    private static final long shapeCount$OFFSET = $LAYOUT.byteOffset(groupElement("shapeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static final long shapeCount$offset() {
        return shapeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static int shapeCount(MemorySegment struct) {
        return struct.get(shapeCount$LAYOUT, shapeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static void shapeCount(MemorySegment struct, int fieldValue) {
        struct.set(shapeCount$LAYOUT, shapeCount$OFFSET, fieldValue);
    }

    private static final OfInt contactCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("contactCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final OfInt contactCount$layout() {
        return contactCount$LAYOUT;
    }

    private static final long contactCount$OFFSET = $LAYOUT.byteOffset(groupElement("contactCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final long contactCount$offset() {
        return contactCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static int contactCount(MemorySegment struct) {
        return struct.get(contactCount$LAYOUT, contactCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static void contactCount(MemorySegment struct, int fieldValue) {
        struct.set(contactCount$LAYOUT, contactCount$OFFSET, fieldValue);
    }

    private static final OfInt jointCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("jointCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static final OfInt jointCount$layout() {
        return jointCount$LAYOUT;
    }

    private static final long jointCount$OFFSET = $LAYOUT.byteOffset(groupElement("jointCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static final long jointCount$offset() {
        return jointCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static int jointCount(MemorySegment struct) {
        return struct.get(jointCount$LAYOUT, jointCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static void jointCount(MemorySegment struct, int fieldValue) {
        struct.set(jointCount$LAYOUT, jointCount$OFFSET, fieldValue);
    }

    private static final OfInt islandCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("islandCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static final OfInt islandCount$layout() {
        return islandCount$LAYOUT;
    }

    private static final long islandCount$OFFSET = $LAYOUT.byteOffset(groupElement("islandCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static final long islandCount$offset() {
        return islandCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static int islandCount(MemorySegment struct) {
        return struct.get(islandCount$LAYOUT, islandCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static void islandCount(MemorySegment struct, int fieldValue) {
        struct.set(islandCount$LAYOUT, islandCount$OFFSET, fieldValue);
    }

    private static final OfInt stackUsed$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stackUsed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static final OfInt stackUsed$layout() {
        return stackUsed$LAYOUT;
    }

    private static final long stackUsed$OFFSET = $LAYOUT.byteOffset(groupElement("stackUsed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static final long stackUsed$offset() {
        return stackUsed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static int stackUsed(MemorySegment struct) {
        return struct.get(stackUsed$LAYOUT, stackUsed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static void stackUsed(MemorySegment struct, int fieldValue) {
        struct.set(stackUsed$LAYOUT, stackUsed$OFFSET, fieldValue);
    }

    private static final OfInt arenaCapacity$LAYOUT = (OfInt)$LAYOUT.select(groupElement("arenaCapacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int arenaCapacity
     * }
     */
    public static final OfInt arenaCapacity$layout() {
        return arenaCapacity$LAYOUT;
    }

    private static final long arenaCapacity$OFFSET = $LAYOUT.byteOffset(groupElement("arenaCapacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int arenaCapacity
     * }
     */
    public static final long arenaCapacity$offset() {
        return arenaCapacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int arenaCapacity
     * }
     */
    public static int arenaCapacity(MemorySegment struct) {
        return struct.get(arenaCapacity$LAYOUT, arenaCapacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int arenaCapacity
     * }
     */
    public static void arenaCapacity(MemorySegment struct, int fieldValue) {
        struct.set(arenaCapacity$LAYOUT, arenaCapacity$OFFSET, fieldValue);
    }

    private static final OfInt staticTreeHeight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("staticTreeHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static final OfInt staticTreeHeight$layout() {
        return staticTreeHeight$LAYOUT;
    }

    private static final long staticTreeHeight$OFFSET = $LAYOUT.byteOffset(groupElement("staticTreeHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static final long staticTreeHeight$offset() {
        return staticTreeHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static int staticTreeHeight(MemorySegment struct) {
        return struct.get(staticTreeHeight$LAYOUT, staticTreeHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static void staticTreeHeight(MemorySegment struct, int fieldValue) {
        struct.set(staticTreeHeight$LAYOUT, staticTreeHeight$OFFSET, fieldValue);
    }

    private static final OfInt treeHeight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("treeHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static final OfInt treeHeight$layout() {
        return treeHeight$LAYOUT;
    }

    private static final long treeHeight$OFFSET = $LAYOUT.byteOffset(groupElement("treeHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static final long treeHeight$offset() {
        return treeHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static int treeHeight(MemorySegment struct) {
        return struct.get(treeHeight$LAYOUT, treeHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static void treeHeight(MemorySegment struct, int fieldValue) {
        struct.set(treeHeight$LAYOUT, treeHeight$OFFSET, fieldValue);
    }

    private static final OfInt satCallCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("satCallCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int satCallCount
     * }
     */
    public static final OfInt satCallCount$layout() {
        return satCallCount$LAYOUT;
    }

    private static final long satCallCount$OFFSET = $LAYOUT.byteOffset(groupElement("satCallCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int satCallCount
     * }
     */
    public static final long satCallCount$offset() {
        return satCallCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int satCallCount
     * }
     */
    public static int satCallCount(MemorySegment struct) {
        return struct.get(satCallCount$LAYOUT, satCallCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int satCallCount
     * }
     */
    public static void satCallCount(MemorySegment struct, int fieldValue) {
        struct.set(satCallCount$LAYOUT, satCallCount$OFFSET, fieldValue);
    }

    private static final OfInt satCacheHitCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("satCacheHitCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int satCacheHitCount
     * }
     */
    public static final OfInt satCacheHitCount$layout() {
        return satCacheHitCount$LAYOUT;
    }

    private static final long satCacheHitCount$OFFSET = $LAYOUT.byteOffset(groupElement("satCacheHitCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int satCacheHitCount
     * }
     */
    public static final long satCacheHitCount$offset() {
        return satCacheHitCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int satCacheHitCount
     * }
     */
    public static int satCacheHitCount(MemorySegment struct) {
        return struct.get(satCacheHitCount$LAYOUT, satCacheHitCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int satCacheHitCount
     * }
     */
    public static void satCacheHitCount(MemorySegment struct, int fieldValue) {
        struct.set(satCacheHitCount$LAYOUT, satCacheHitCount$OFFSET, fieldValue);
    }

    private static final OfInt byteCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("byteCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final OfInt byteCount$layout() {
        return byteCount$LAYOUT;
    }

    private static final long byteCount$OFFSET = $LAYOUT.byteOffset(groupElement("byteCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final long byteCount$offset() {
        return byteCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static int byteCount(MemorySegment struct) {
        return struct.get(byteCount$LAYOUT, byteCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static void byteCount(MemorySegment struct, int fieldValue) {
        struct.set(byteCount$LAYOUT, byteCount$OFFSET, fieldValue);
    }

    private static final OfInt taskCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("taskCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static final OfInt taskCount$layout() {
        return taskCount$LAYOUT;
    }

    private static final long taskCount$OFFSET = $LAYOUT.byteOffset(groupElement("taskCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static final long taskCount$offset() {
        return taskCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static int taskCount(MemorySegment struct) {
        return struct.get(taskCount$LAYOUT, taskCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static void taskCount(MemorySegment struct, int fieldValue) {
        struct.set(taskCount$LAYOUT, taskCount$OFFSET, fieldValue);
    }

    private static final SequenceLayout colorCounts$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("colorCounts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static final SequenceLayout colorCounts$layout() {
        return colorCounts$LAYOUT;
    }

    private static final long colorCounts$OFFSET = $LAYOUT.byteOffset(groupElement("colorCounts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static final long colorCounts$offset() {
        return colorCounts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static MemorySegment colorCounts(MemorySegment struct) {
        return struct.asSlice(colorCounts$OFFSET, colorCounts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static void colorCounts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, colorCounts$OFFSET, colorCounts$LAYOUT.byteSize());
    }

    private static long[] colorCounts$DIMS = { 24 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static long[] colorCounts$dimensions() {
        return colorCounts$DIMS;
    }
    private static final VarHandle colorCounts$ELEM_HANDLE = colorCounts$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static int colorCounts(MemorySegment struct, long index0) {
        return (int)colorCounts$ELEM_HANDLE.get(struct, colorCounts$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int colorCounts[24]
     * }
     */
    public static void colorCounts(MemorySegment struct, long index0, int fieldValue) {
        colorCounts$ELEM_HANDLE.set(struct, colorCounts$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout manifoldCounts$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("manifoldCounts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static final SequenceLayout manifoldCounts$layout() {
        return manifoldCounts$LAYOUT;
    }

    private static final long manifoldCounts$OFFSET = $LAYOUT.byteOffset(groupElement("manifoldCounts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static final long manifoldCounts$offset() {
        return manifoldCounts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static MemorySegment manifoldCounts(MemorySegment struct) {
        return struct.asSlice(manifoldCounts$OFFSET, manifoldCounts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static void manifoldCounts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, manifoldCounts$OFFSET, manifoldCounts$LAYOUT.byteSize());
    }

    private static long[] manifoldCounts$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static long[] manifoldCounts$dimensions() {
        return manifoldCounts$DIMS;
    }
    private static final VarHandle manifoldCounts$ELEM_HANDLE = manifoldCounts$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static int manifoldCounts(MemorySegment struct, long index0) {
        return (int)manifoldCounts$ELEM_HANDLE.get(struct, manifoldCounts$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int manifoldCounts[8]
     * }
     */
    public static void manifoldCounts(MemorySegment struct, long index0, int fieldValue) {
        manifoldCounts$ELEM_HANDLE.set(struct, manifoldCounts$OFFSET, index0, fieldValue);
    }

    private static final OfInt awakeContactCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("awakeContactCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int awakeContactCount
     * }
     */
    public static final OfInt awakeContactCount$layout() {
        return awakeContactCount$LAYOUT;
    }

    private static final long awakeContactCount$OFFSET = $LAYOUT.byteOffset(groupElement("awakeContactCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int awakeContactCount
     * }
     */
    public static final long awakeContactCount$offset() {
        return awakeContactCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int awakeContactCount
     * }
     */
    public static int awakeContactCount(MemorySegment struct) {
        return struct.get(awakeContactCount$LAYOUT, awakeContactCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int awakeContactCount
     * }
     */
    public static void awakeContactCount(MemorySegment struct, int fieldValue) {
        struct.set(awakeContactCount$LAYOUT, awakeContactCount$OFFSET, fieldValue);
    }

    private static final OfInt recycledContactCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("recycledContactCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int recycledContactCount
     * }
     */
    public static final OfInt recycledContactCount$layout() {
        return recycledContactCount$LAYOUT;
    }

    private static final long recycledContactCount$OFFSET = $LAYOUT.byteOffset(groupElement("recycledContactCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int recycledContactCount
     * }
     */
    public static final long recycledContactCount$offset() {
        return recycledContactCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int recycledContactCount
     * }
     */
    public static int recycledContactCount(MemorySegment struct) {
        return struct.get(recycledContactCount$LAYOUT, recycledContactCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int recycledContactCount
     * }
     */
    public static void recycledContactCount(MemorySegment struct, int fieldValue) {
        struct.set(recycledContactCount$LAYOUT, recycledContactCount$OFFSET, fieldValue);
    }

    private static final OfInt distanceIterations$LAYOUT = (OfInt)$LAYOUT.select(groupElement("distanceIterations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int distanceIterations
     * }
     */
    public static final OfInt distanceIterations$layout() {
        return distanceIterations$LAYOUT;
    }

    private static final long distanceIterations$OFFSET = $LAYOUT.byteOffset(groupElement("distanceIterations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int distanceIterations
     * }
     */
    public static final long distanceIterations$offset() {
        return distanceIterations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int distanceIterations
     * }
     */
    public static int distanceIterations(MemorySegment struct) {
        return struct.get(distanceIterations$LAYOUT, distanceIterations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int distanceIterations
     * }
     */
    public static void distanceIterations(MemorySegment struct, int fieldValue) {
        struct.set(distanceIterations$LAYOUT, distanceIterations$OFFSET, fieldValue);
    }

    private static final OfInt pushBackIterations$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pushBackIterations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int pushBackIterations
     * }
     */
    public static final OfInt pushBackIterations$layout() {
        return pushBackIterations$LAYOUT;
    }

    private static final long pushBackIterations$OFFSET = $LAYOUT.byteOffset(groupElement("pushBackIterations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int pushBackIterations
     * }
     */
    public static final long pushBackIterations$offset() {
        return pushBackIterations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pushBackIterations
     * }
     */
    public static int pushBackIterations(MemorySegment struct) {
        return struct.get(pushBackIterations$LAYOUT, pushBackIterations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pushBackIterations
     * }
     */
    public static void pushBackIterations(MemorySegment struct, int fieldValue) {
        struct.set(pushBackIterations$LAYOUT, pushBackIterations$OFFSET, fieldValue);
    }

    private static final OfInt rootIterations$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rootIterations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int rootIterations
     * }
     */
    public static final OfInt rootIterations$layout() {
        return rootIterations$LAYOUT;
    }

    private static final long rootIterations$OFFSET = $LAYOUT.byteOffset(groupElement("rootIterations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int rootIterations
     * }
     */
    public static final long rootIterations$offset() {
        return rootIterations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int rootIterations
     * }
     */
    public static int rootIterations(MemorySegment struct) {
        return struct.get(rootIterations$LAYOUT, rootIterations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int rootIterations
     * }
     */
    public static void rootIterations(MemorySegment struct, int fieldValue) {
        struct.set(rootIterations$LAYOUT, rootIterations$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

