// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3CollisionPlane {
 *     b3Plane plane;
 *     float pushLimit;
 *     float push;
 *     _Bool clipVelocity;
 * }
 * }
 */
public class b3CollisionPlane {

    b3CollisionPlane() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Plane.layout().withName("plane"),
        Box3D.C_FLOAT.withName("pushLimit"),
        Box3D.C_FLOAT.withName("push"),
        Box3D.C_BOOL.withName("clipVelocity"),
        MemoryLayout.paddingLayout(3)
    ).withName("b3CollisionPlane");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout plane$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("plane"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static final GroupLayout plane$layout() {
        return plane$LAYOUT;
    }

    private static final long plane$OFFSET = $LAYOUT.byteOffset(groupElement("plane"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static final long plane$offset() {
        return plane$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static MemorySegment plane(MemorySegment struct) {
        return struct.asSlice(plane$OFFSET, plane$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static void plane(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, plane$OFFSET, plane$LAYOUT.byteSize());
    }

    private static final OfFloat pushLimit$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("pushLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float pushLimit
     * }
     */
    public static final OfFloat pushLimit$layout() {
        return pushLimit$LAYOUT;
    }

    private static final long pushLimit$OFFSET = $LAYOUT.byteOffset(groupElement("pushLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float pushLimit
     * }
     */
    public static final long pushLimit$offset() {
        return pushLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float pushLimit
     * }
     */
    public static float pushLimit(MemorySegment struct) {
        return struct.get(pushLimit$LAYOUT, pushLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float pushLimit
     * }
     */
    public static void pushLimit(MemorySegment struct, float fieldValue) {
        struct.set(pushLimit$LAYOUT, pushLimit$OFFSET, fieldValue);
    }

    private static final OfFloat push$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("push"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float push
     * }
     */
    public static final OfFloat push$layout() {
        return push$LAYOUT;
    }

    private static final long push$OFFSET = $LAYOUT.byteOffset(groupElement("push"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float push
     * }
     */
    public static final long push$offset() {
        return push$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float push
     * }
     */
    public static float push(MemorySegment struct) {
        return struct.get(push$LAYOUT, push$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float push
     * }
     */
    public static void push(MemorySegment struct, float fieldValue) {
        struct.set(push$LAYOUT, push$OFFSET, fieldValue);
    }

    private static final OfBoolean clipVelocity$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("clipVelocity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool clipVelocity
     * }
     */
    public static final OfBoolean clipVelocity$layout() {
        return clipVelocity$LAYOUT;
    }

    private static final long clipVelocity$OFFSET = $LAYOUT.byteOffset(groupElement("clipVelocity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool clipVelocity
     * }
     */
    public static final long clipVelocity$offset() {
        return clipVelocity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool clipVelocity
     * }
     */
    public static boolean clipVelocity(MemorySegment struct) {
        return struct.get(clipVelocity$LAYOUT, clipVelocity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool clipVelocity
     * }
     */
    public static void clipVelocity(MemorySegment struct, boolean fieldValue) {
        struct.set(clipVelocity$LAYOUT, clipVelocity$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

