// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3CompoundCapsule {
 *     b3Capsule capsule;
 *     int materialIndex;
 * }
 * }
 */
public class b3CompoundCapsule {

    b3CompoundCapsule() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Capsule.layout().withName("capsule"),
        Box3D.C_INT.withName("materialIndex")
    ).withName("b3CompoundCapsule");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout capsule$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("capsule"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static final GroupLayout capsule$layout() {
        return capsule$LAYOUT;
    }

    private static final long capsule$OFFSET = $LAYOUT.byteOffset(groupElement("capsule"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static final long capsule$offset() {
        return capsule$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static MemorySegment capsule(MemorySegment struct) {
        return struct.asSlice(capsule$OFFSET, capsule$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Capsule capsule
     * }
     */
    public static void capsule(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, capsule$OFFSET, capsule$LAYOUT.byteSize());
    }

    private static final OfInt materialIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("materialIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static final OfInt materialIndex$layout() {
        return materialIndex$LAYOUT;
    }

    private static final long materialIndex$OFFSET = $LAYOUT.byteOffset(groupElement("materialIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static final long materialIndex$offset() {
        return materialIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static int materialIndex(MemorySegment struct) {
        return struct.get(materialIndex$LAYOUT, materialIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static void materialIndex(MemorySegment struct, int fieldValue) {
        struct.set(materialIndex$LAYOUT, materialIndex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

