// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3ContactData {
 *     b3ContactId contactId;
 *     b3ShapeId shapeIdA;
 *     b3ShapeId shapeIdB;
 *     const struct b3Manifold *manifolds;
 *     int manifoldCount;
 * }
 * }
 */
public class b3ContactData {

    b3ContactData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3ContactId.layout().withName("contactId"),
        b3ShapeId.layout().withName("shapeIdA"),
        b3ShapeId.layout().withName("shapeIdB"),
        MemoryLayout.paddingLayout(4),
        Box3D.C_POINTER.withName("manifolds"),
        Box3D.C_INT.withName("manifoldCount"),
        MemoryLayout.paddingLayout(4)
    ).withName("b3ContactData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout contactId$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("contactId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ContactId contactId
     * }
     */
    public static final GroupLayout contactId$layout() {
        return contactId$LAYOUT;
    }

    private static final long contactId$OFFSET = $LAYOUT.byteOffset(groupElement("contactId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ContactId contactId
     * }
     */
    public static final long contactId$offset() {
        return contactId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ContactId contactId
     * }
     */
    public static MemorySegment contactId(MemorySegment struct) {
        return struct.asSlice(contactId$OFFSET, contactId$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ContactId contactId
     * }
     */
    public static void contactId(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, contactId$OFFSET, contactId$LAYOUT.byteSize());
    }

    private static final GroupLayout shapeIdA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("shapeIdA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdA
     * }
     */
    public static final GroupLayout shapeIdA$layout() {
        return shapeIdA$LAYOUT;
    }

    private static final long shapeIdA$OFFSET = $LAYOUT.byteOffset(groupElement("shapeIdA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdA
     * }
     */
    public static final long shapeIdA$offset() {
        return shapeIdA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdA
     * }
     */
    public static MemorySegment shapeIdA(MemorySegment struct) {
        return struct.asSlice(shapeIdA$OFFSET, shapeIdA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdA
     * }
     */
    public static void shapeIdA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shapeIdA$OFFSET, shapeIdA$LAYOUT.byteSize());
    }

    private static final GroupLayout shapeIdB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("shapeIdB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdB
     * }
     */
    public static final GroupLayout shapeIdB$layout() {
        return shapeIdB$LAYOUT;
    }

    private static final long shapeIdB$OFFSET = $LAYOUT.byteOffset(groupElement("shapeIdB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdB
     * }
     */
    public static final long shapeIdB$offset() {
        return shapeIdB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdB
     * }
     */
    public static MemorySegment shapeIdB(MemorySegment struct) {
        return struct.asSlice(shapeIdB$OFFSET, shapeIdB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeId shapeIdB
     * }
     */
    public static void shapeIdB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shapeIdB$OFFSET, shapeIdB$LAYOUT.byteSize());
    }

    private static final AddressLayout manifolds$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("manifolds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct b3Manifold *manifolds
     * }
     */
    public static final AddressLayout manifolds$layout() {
        return manifolds$LAYOUT;
    }

    private static final long manifolds$OFFSET = $LAYOUT.byteOffset(groupElement("manifolds"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct b3Manifold *manifolds
     * }
     */
    public static final long manifolds$offset() {
        return manifolds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct b3Manifold *manifolds
     * }
     */
    public static MemorySegment manifolds(MemorySegment struct) {
        return struct.get(manifolds$LAYOUT, manifolds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct b3Manifold *manifolds
     * }
     */
    public static void manifolds(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(manifolds$LAYOUT, manifolds$OFFSET, fieldValue);
    }

    private static final OfInt manifoldCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("manifoldCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int manifoldCount
     * }
     */
    public static final OfInt manifoldCount$layout() {
        return manifoldCount$LAYOUT;
    }

    private static final long manifoldCount$OFFSET = $LAYOUT.byteOffset(groupElement("manifoldCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int manifoldCount
     * }
     */
    public static final long manifoldCount$offset() {
        return manifoldCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int manifoldCount
     * }
     */
    public static int manifoldCount(MemorySegment struct) {
        return struct.get(manifoldCount$LAYOUT, manifoldCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int manifoldCount
     * }
     */
    public static void manifoldCount(MemorySegment struct, int fieldValue) {
        struct.set(manifoldCount$LAYOUT, manifoldCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

