// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef _Bool (b3CompoundQueryFcn)(const b3CompoundData *, int, void *)
 * }
 */
public final class b3CompoundQueryFcn {

    private b3CompoundQueryFcn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(MemorySegment compound, int childIndex, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box3D.C_BOOL,
        Box3D.C_POINTER,
        Box3D.C_INT,
        Box3D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box3D.upcallHandle(b3CompoundQueryFcn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(b3CompoundQueryFcn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr, MemorySegment compound, int childIndex, MemorySegment context) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, compound, childIndex, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

