// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3DistanceInput {
 *     b3ShapeProxy proxyA;
 *     b3ShapeProxy proxyB;
 *     b3Transform transform;
 *     _Bool useRadii;
 * }
 * }
 */
public class b3DistanceInput {

    b3DistanceInput() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3ShapeProxy.layout().withName("proxyA"),
        b3ShapeProxy.layout().withName("proxyB"),
        b3Transform.layout().withName("transform"),
        Box3D.C_BOOL.withName("useRadii"),
        MemoryLayout.paddingLayout(3)
    ).withName("b3DistanceInput");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout proxyA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static final GroupLayout proxyA$layout() {
        return proxyA$LAYOUT;
    }

    private static final long proxyA$OFFSET = $LAYOUT.byteOffset(groupElement("proxyA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static final long proxyA$offset() {
        return proxyA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static MemorySegment proxyA(MemorySegment struct) {
        return struct.asSlice(proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static void proxyA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    private static final GroupLayout proxyB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static final GroupLayout proxyB$layout() {
        return proxyB$LAYOUT;
    }

    private static final long proxyB$OFFSET = $LAYOUT.byteOffset(groupElement("proxyB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static final long proxyB$offset() {
        return proxyB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static MemorySegment proxyB(MemorySegment struct) {
        return struct.asSlice(proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static void proxyB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    private static final GroupLayout transform$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transform"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final GroupLayout transform$layout() {
        return transform$LAYOUT;
    }

    private static final long transform$OFFSET = $LAYOUT.byteOffset(groupElement("transform"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final long transform$offset() {
        return transform$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static MemorySegment transform(MemorySegment struct) {
        return struct.asSlice(transform$OFFSET, transform$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static void transform(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transform$OFFSET, transform$LAYOUT.byteSize());
    }

    private static final OfBoolean useRadii$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("useRadii"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static final OfBoolean useRadii$layout() {
        return useRadii$LAYOUT;
    }

    private static final long useRadii$OFFSET = $LAYOUT.byteOffset(groupElement("useRadii"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static final long useRadii$offset() {
        return useRadii$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static boolean useRadii(MemorySegment struct) {
        return struct.get(useRadii$LAYOUT, useRadii$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static void useRadii(MemorySegment struct, boolean fieldValue) {
        struct.set(useRadii$LAYOUT, useRadii$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

