// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef float (b3FrictionCallback)(float, uint64_t, float, uint64_t)
 * }
 */
public final class b3FrictionCallback {

    private b3FrictionCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(float frictionA, long userMaterialIdA, float frictionB, long userMaterialIdB);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box3D.C_FLOAT,
        Box3D.C_FLOAT,
        Box3D.C_LONG_LONG,
        Box3D.C_FLOAT,
        Box3D.C_LONG_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box3D.upcallHandle(b3FrictionCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(b3FrictionCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr, float frictionA, long userMaterialIdA, float frictionB, long userMaterialIdB) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, frictionA, userMaterialIdA, frictionB, userMaterialIdB);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

