// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3HeightFieldData {
 *     uint64_t version;
 *     uint64_t hash;
 *     int byteCount;
 *     b3AABB aabb;
 *     float minHeight;
 *     float maxHeight;
 *     float heightScale;
 *     b3Vec3 scale;
 *     int32_t columnCount;
 *     int32_t rowCount;
 *     int32_t heightsOffset;
 *     int32_t materialOffset;
 *     int32_t flagsOffset;
 *     uint8_t clockwise;
 *     uint8_t padding[7];
 * }
 * }
 */
public class b3HeightFieldData {

    b3HeightFieldData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_LONG_LONG.withName("version"),
        Box3D.C_LONG_LONG.withName("hash"),
        Box3D.C_INT.withName("byteCount"),
        b3AABB.layout().withName("aabb"),
        Box3D.C_FLOAT.withName("minHeight"),
        Box3D.C_FLOAT.withName("maxHeight"),
        Box3D.C_FLOAT.withName("heightScale"),
        b3Vec3.layout().withName("scale"),
        Box3D.C_INT.withName("columnCount"),
        Box3D.C_INT.withName("rowCount"),
        Box3D.C_INT.withName("heightsOffset"),
        Box3D.C_INT.withName("materialOffset"),
        Box3D.C_INT.withName("flagsOffset"),
        Box3D.C_CHAR.withName("clockwise"),
        MemoryLayout.sequenceLayout(7, Box3D.C_CHAR).withName("padding")
    ).withName("b3HeightFieldData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong version$LAYOUT = (OfLong)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static final OfLong version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static long version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static void version(MemorySegment struct, long fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfLong hash$LAYOUT = (OfLong)$LAYOUT.select(groupElement("hash"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static final OfLong hash$layout() {
        return hash$LAYOUT;
    }

    private static final long hash$OFFSET = $LAYOUT.byteOffset(groupElement("hash"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static final long hash$offset() {
        return hash$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static long hash(MemorySegment struct) {
        return struct.get(hash$LAYOUT, hash$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static void hash(MemorySegment struct, long fieldValue) {
        struct.set(hash$LAYOUT, hash$OFFSET, fieldValue);
    }

    private static final OfInt byteCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("byteCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final OfInt byteCount$layout() {
        return byteCount$LAYOUT;
    }

    private static final long byteCount$OFFSET = $LAYOUT.byteOffset(groupElement("byteCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final long byteCount$offset() {
        return byteCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static int byteCount(MemorySegment struct) {
        return struct.get(byteCount$LAYOUT, byteCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static void byteCount(MemorySegment struct, int fieldValue) {
        struct.set(byteCount$LAYOUT, byteCount$OFFSET, fieldValue);
    }

    private static final GroupLayout aabb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("aabb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final GroupLayout aabb$layout() {
        return aabb$LAYOUT;
    }

    private static final long aabb$OFFSET = $LAYOUT.byteOffset(groupElement("aabb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final long aabb$offset() {
        return aabb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static MemorySegment aabb(MemorySegment struct) {
        return struct.asSlice(aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static void aabb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    private static final OfFloat minHeight$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("minHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float minHeight
     * }
     */
    public static final OfFloat minHeight$layout() {
        return minHeight$LAYOUT;
    }

    private static final long minHeight$OFFSET = $LAYOUT.byteOffset(groupElement("minHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float minHeight
     * }
     */
    public static final long minHeight$offset() {
        return minHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float minHeight
     * }
     */
    public static float minHeight(MemorySegment struct) {
        return struct.get(minHeight$LAYOUT, minHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float minHeight
     * }
     */
    public static void minHeight(MemorySegment struct, float fieldValue) {
        struct.set(minHeight$LAYOUT, minHeight$OFFSET, fieldValue);
    }

    private static final OfFloat maxHeight$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxHeight
     * }
     */
    public static final OfFloat maxHeight$layout() {
        return maxHeight$LAYOUT;
    }

    private static final long maxHeight$OFFSET = $LAYOUT.byteOffset(groupElement("maxHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxHeight
     * }
     */
    public static final long maxHeight$offset() {
        return maxHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxHeight
     * }
     */
    public static float maxHeight(MemorySegment struct) {
        return struct.get(maxHeight$LAYOUT, maxHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxHeight
     * }
     */
    public static void maxHeight(MemorySegment struct, float fieldValue) {
        struct.set(maxHeight$LAYOUT, maxHeight$OFFSET, fieldValue);
    }

    private static final OfFloat heightScale$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("heightScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float heightScale
     * }
     */
    public static final OfFloat heightScale$layout() {
        return heightScale$LAYOUT;
    }

    private static final long heightScale$OFFSET = $LAYOUT.byteOffset(groupElement("heightScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float heightScale
     * }
     */
    public static final long heightScale$offset() {
        return heightScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float heightScale
     * }
     */
    public static float heightScale(MemorySegment struct) {
        return struct.get(heightScale$LAYOUT, heightScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float heightScale
     * }
     */
    public static void heightScale(MemorySegment struct, float fieldValue) {
        struct.set(heightScale$LAYOUT, heightScale$OFFSET, fieldValue);
    }

    private static final GroupLayout scale$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("scale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static final GroupLayout scale$layout() {
        return scale$LAYOUT;
    }

    private static final long scale$OFFSET = $LAYOUT.byteOffset(groupElement("scale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static final long scale$offset() {
        return scale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static MemorySegment scale(MemorySegment struct) {
        return struct.asSlice(scale$OFFSET, scale$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static void scale(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, scale$OFFSET, scale$LAYOUT.byteSize());
    }

    private static final OfInt columnCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("columnCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t columnCount
     * }
     */
    public static final OfInt columnCount$layout() {
        return columnCount$LAYOUT;
    }

    private static final long columnCount$OFFSET = $LAYOUT.byteOffset(groupElement("columnCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t columnCount
     * }
     */
    public static final long columnCount$offset() {
        return columnCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t columnCount
     * }
     */
    public static int columnCount(MemorySegment struct) {
        return struct.get(columnCount$LAYOUT, columnCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t columnCount
     * }
     */
    public static void columnCount(MemorySegment struct, int fieldValue) {
        struct.set(columnCount$LAYOUT, columnCount$OFFSET, fieldValue);
    }

    private static final OfInt rowCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rowCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t rowCount
     * }
     */
    public static final OfInt rowCount$layout() {
        return rowCount$LAYOUT;
    }

    private static final long rowCount$OFFSET = $LAYOUT.byteOffset(groupElement("rowCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t rowCount
     * }
     */
    public static final long rowCount$offset() {
        return rowCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t rowCount
     * }
     */
    public static int rowCount(MemorySegment struct) {
        return struct.get(rowCount$LAYOUT, rowCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t rowCount
     * }
     */
    public static void rowCount(MemorySegment struct, int fieldValue) {
        struct.set(rowCount$LAYOUT, rowCount$OFFSET, fieldValue);
    }

    private static final OfInt heightsOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("heightsOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t heightsOffset
     * }
     */
    public static final OfInt heightsOffset$layout() {
        return heightsOffset$LAYOUT;
    }

    private static final long heightsOffset$OFFSET = $LAYOUT.byteOffset(groupElement("heightsOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t heightsOffset
     * }
     */
    public static final long heightsOffset$offset() {
        return heightsOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t heightsOffset
     * }
     */
    public static int heightsOffset(MemorySegment struct) {
        return struct.get(heightsOffset$LAYOUT, heightsOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t heightsOffset
     * }
     */
    public static void heightsOffset(MemorySegment struct, int fieldValue) {
        struct.set(heightsOffset$LAYOUT, heightsOffset$OFFSET, fieldValue);
    }

    private static final OfInt materialOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("materialOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t materialOffset
     * }
     */
    public static final OfInt materialOffset$layout() {
        return materialOffset$LAYOUT;
    }

    private static final long materialOffset$OFFSET = $LAYOUT.byteOffset(groupElement("materialOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t materialOffset
     * }
     */
    public static final long materialOffset$offset() {
        return materialOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t materialOffset
     * }
     */
    public static int materialOffset(MemorySegment struct) {
        return struct.get(materialOffset$LAYOUT, materialOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t materialOffset
     * }
     */
    public static void materialOffset(MemorySegment struct, int fieldValue) {
        struct.set(materialOffset$LAYOUT, materialOffset$OFFSET, fieldValue);
    }

    private static final OfInt flagsOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flagsOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t flagsOffset
     * }
     */
    public static final OfInt flagsOffset$layout() {
        return flagsOffset$LAYOUT;
    }

    private static final long flagsOffset$OFFSET = $LAYOUT.byteOffset(groupElement("flagsOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t flagsOffset
     * }
     */
    public static final long flagsOffset$offset() {
        return flagsOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t flagsOffset
     * }
     */
    public static int flagsOffset(MemorySegment struct) {
        return struct.get(flagsOffset$LAYOUT, flagsOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t flagsOffset
     * }
     */
    public static void flagsOffset(MemorySegment struct, int fieldValue) {
        struct.set(flagsOffset$LAYOUT, flagsOffset$OFFSET, fieldValue);
    }

    private static final OfByte clockwise$LAYOUT = (OfByte)$LAYOUT.select(groupElement("clockwise"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t clockwise
     * }
     */
    public static final OfByte clockwise$layout() {
        return clockwise$LAYOUT;
    }

    private static final long clockwise$OFFSET = $LAYOUT.byteOffset(groupElement("clockwise"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t clockwise
     * }
     */
    public static final long clockwise$offset() {
        return clockwise$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t clockwise
     * }
     */
    public static byte clockwise(MemorySegment struct) {
        return struct.get(clockwise$LAYOUT, clockwise$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t clockwise
     * }
     */
    public static void clockwise(MemorySegment struct, byte fieldValue) {
        struct.set(clockwise$LAYOUT, clockwise$OFFSET, fieldValue);
    }

    private static final SequenceLayout padding$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("padding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static final SequenceLayout padding$layout() {
        return padding$LAYOUT;
    }

    private static final long padding$OFFSET = $LAYOUT.byteOffset(groupElement("padding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static final long padding$offset() {
        return padding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static MemorySegment padding(MemorySegment struct) {
        return struct.asSlice(padding$OFFSET, padding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static void padding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, padding$OFFSET, padding$LAYOUT.byteSize());
    }

    private static long[] padding$DIMS = { 7 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static long[] padding$dimensions() {
        return padding$DIMS;
    }
    private static final VarHandle padding$ELEM_HANDLE = padding$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static byte padding(MemorySegment struct, long index0) {
        return (byte)padding$ELEM_HANDLE.get(struct, padding$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t padding[7]
     * }
     */
    public static void padding(MemorySegment struct, long index0, byte fieldValue) {
        padding$ELEM_HANDLE.set(struct, padding$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

