// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3HeightFieldDef {
 *     float *heights;
 *     uint8_t *materialIndices;
 *     b3Vec3 scale;
 *     int countX;
 *     int countZ;
 *     float globalMinimumHeight;
 *     float globalMaximumHeight;
 *     _Bool clockwiseWinding;
 * }
 * }
 */
public class b3HeightFieldDef {

    b3HeightFieldDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_POINTER.withName("heights"),
        Box3D.C_POINTER.withName("materialIndices"),
        b3Vec3.layout().withName("scale"),
        Box3D.C_INT.withName("countX"),
        Box3D.C_INT.withName("countZ"),
        Box3D.C_FLOAT.withName("globalMinimumHeight"),
        Box3D.C_FLOAT.withName("globalMaximumHeight"),
        Box3D.C_BOOL.withName("clockwiseWinding"),
        MemoryLayout.paddingLayout(3)
    ).withName("b3HeightFieldDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout heights$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("heights"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float *heights
     * }
     */
    public static final AddressLayout heights$layout() {
        return heights$LAYOUT;
    }

    private static final long heights$OFFSET = $LAYOUT.byteOffset(groupElement("heights"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float *heights
     * }
     */
    public static final long heights$offset() {
        return heights$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float *heights
     * }
     */
    public static MemorySegment heights(MemorySegment struct) {
        return struct.get(heights$LAYOUT, heights$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float *heights
     * }
     */
    public static void heights(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(heights$LAYOUT, heights$OFFSET, fieldValue);
    }

    private static final AddressLayout materialIndices$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("materialIndices"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t *materialIndices
     * }
     */
    public static final AddressLayout materialIndices$layout() {
        return materialIndices$LAYOUT;
    }

    private static final long materialIndices$OFFSET = $LAYOUT.byteOffset(groupElement("materialIndices"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t *materialIndices
     * }
     */
    public static final long materialIndices$offset() {
        return materialIndices$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t *materialIndices
     * }
     */
    public static MemorySegment materialIndices(MemorySegment struct) {
        return struct.get(materialIndices$LAYOUT, materialIndices$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t *materialIndices
     * }
     */
    public static void materialIndices(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(materialIndices$LAYOUT, materialIndices$OFFSET, fieldValue);
    }

    private static final GroupLayout scale$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("scale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static final GroupLayout scale$layout() {
        return scale$LAYOUT;
    }

    private static final long scale$OFFSET = $LAYOUT.byteOffset(groupElement("scale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static final long scale$offset() {
        return scale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static MemorySegment scale(MemorySegment struct) {
        return struct.asSlice(scale$OFFSET, scale$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 scale
     * }
     */
    public static void scale(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, scale$OFFSET, scale$LAYOUT.byteSize());
    }

    private static final OfInt countX$LAYOUT = (OfInt)$LAYOUT.select(groupElement("countX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int countX
     * }
     */
    public static final OfInt countX$layout() {
        return countX$LAYOUT;
    }

    private static final long countX$OFFSET = $LAYOUT.byteOffset(groupElement("countX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int countX
     * }
     */
    public static final long countX$offset() {
        return countX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int countX
     * }
     */
    public static int countX(MemorySegment struct) {
        return struct.get(countX$LAYOUT, countX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int countX
     * }
     */
    public static void countX(MemorySegment struct, int fieldValue) {
        struct.set(countX$LAYOUT, countX$OFFSET, fieldValue);
    }

    private static final OfInt countZ$LAYOUT = (OfInt)$LAYOUT.select(groupElement("countZ"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int countZ
     * }
     */
    public static final OfInt countZ$layout() {
        return countZ$LAYOUT;
    }

    private static final long countZ$OFFSET = $LAYOUT.byteOffset(groupElement("countZ"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int countZ
     * }
     */
    public static final long countZ$offset() {
        return countZ$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int countZ
     * }
     */
    public static int countZ(MemorySegment struct) {
        return struct.get(countZ$LAYOUT, countZ$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int countZ
     * }
     */
    public static void countZ(MemorySegment struct, int fieldValue) {
        struct.set(countZ$LAYOUT, countZ$OFFSET, fieldValue);
    }

    private static final OfFloat globalMinimumHeight$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("globalMinimumHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float globalMinimumHeight
     * }
     */
    public static final OfFloat globalMinimumHeight$layout() {
        return globalMinimumHeight$LAYOUT;
    }

    private static final long globalMinimumHeight$OFFSET = $LAYOUT.byteOffset(groupElement("globalMinimumHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float globalMinimumHeight
     * }
     */
    public static final long globalMinimumHeight$offset() {
        return globalMinimumHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float globalMinimumHeight
     * }
     */
    public static float globalMinimumHeight(MemorySegment struct) {
        return struct.get(globalMinimumHeight$LAYOUT, globalMinimumHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float globalMinimumHeight
     * }
     */
    public static void globalMinimumHeight(MemorySegment struct, float fieldValue) {
        struct.set(globalMinimumHeight$LAYOUT, globalMinimumHeight$OFFSET, fieldValue);
    }

    private static final OfFloat globalMaximumHeight$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("globalMaximumHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float globalMaximumHeight
     * }
     */
    public static final OfFloat globalMaximumHeight$layout() {
        return globalMaximumHeight$LAYOUT;
    }

    private static final long globalMaximumHeight$OFFSET = $LAYOUT.byteOffset(groupElement("globalMaximumHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float globalMaximumHeight
     * }
     */
    public static final long globalMaximumHeight$offset() {
        return globalMaximumHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float globalMaximumHeight
     * }
     */
    public static float globalMaximumHeight(MemorySegment struct) {
        return struct.get(globalMaximumHeight$LAYOUT, globalMaximumHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float globalMaximumHeight
     * }
     */
    public static void globalMaximumHeight(MemorySegment struct, float fieldValue) {
        struct.set(globalMaximumHeight$LAYOUT, globalMaximumHeight$OFFSET, fieldValue);
    }

    private static final OfBoolean clockwiseWinding$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("clockwiseWinding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool clockwiseWinding
     * }
     */
    public static final OfBoolean clockwiseWinding$layout() {
        return clockwiseWinding$LAYOUT;
    }

    private static final long clockwiseWinding$OFFSET = $LAYOUT.byteOffset(groupElement("clockwiseWinding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool clockwiseWinding
     * }
     */
    public static final long clockwiseWinding$offset() {
        return clockwiseWinding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool clockwiseWinding
     * }
     */
    public static boolean clockwiseWinding(MemorySegment struct) {
        return struct.get(clockwiseWinding$LAYOUT, clockwiseWinding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool clockwiseWinding
     * }
     */
    public static void clockwiseWinding(MemorySegment struct, boolean fieldValue) {
        struct.set(clockwiseWinding$LAYOUT, clockwiseWinding$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

