// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3HullHalfEdge {
 *     uint8_t next;
 *     uint8_t twin;
 *     uint8_t origin;
 *     uint8_t face;
 * }
 * }
 */
public class b3HullHalfEdge {

    b3HullHalfEdge() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_CHAR.withName("next"),
        Box3D.C_CHAR.withName("twin"),
        Box3D.C_CHAR.withName("origin"),
        Box3D.C_CHAR.withName("face")
    ).withName("b3HullHalfEdge");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte next$LAYOUT = (OfByte)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t next
     * }
     */
    public static final OfByte next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t next
     * }
     */
    public static byte next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t next
     * }
     */
    public static void next(MemorySegment struct, byte fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    private static final OfByte twin$LAYOUT = (OfByte)$LAYOUT.select(groupElement("twin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t twin
     * }
     */
    public static final OfByte twin$layout() {
        return twin$LAYOUT;
    }

    private static final long twin$OFFSET = $LAYOUT.byteOffset(groupElement("twin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t twin
     * }
     */
    public static final long twin$offset() {
        return twin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t twin
     * }
     */
    public static byte twin(MemorySegment struct) {
        return struct.get(twin$LAYOUT, twin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t twin
     * }
     */
    public static void twin(MemorySegment struct, byte fieldValue) {
        struct.set(twin$LAYOUT, twin$OFFSET, fieldValue);
    }

    private static final OfByte origin$LAYOUT = (OfByte)$LAYOUT.select(groupElement("origin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t origin
     * }
     */
    public static final OfByte origin$layout() {
        return origin$LAYOUT;
    }

    private static final long origin$OFFSET = $LAYOUT.byteOffset(groupElement("origin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t origin
     * }
     */
    public static final long origin$offset() {
        return origin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t origin
     * }
     */
    public static byte origin(MemorySegment struct) {
        return struct.get(origin$LAYOUT, origin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t origin
     * }
     */
    public static void origin(MemorySegment struct, byte fieldValue) {
        struct.set(origin$LAYOUT, origin$OFFSET, fieldValue);
    }

    private static final OfByte face$LAYOUT = (OfByte)$LAYOUT.select(groupElement("face"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t face
     * }
     */
    public static final OfByte face$layout() {
        return face$LAYOUT;
    }

    private static final long face$OFFSET = $LAYOUT.byteOffset(groupElement("face"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t face
     * }
     */
    public static final long face$offset() {
        return face$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t face
     * }
     */
    public static byte face(MemorySegment struct) {
        return struct.get(face$LAYOUT, face$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t face
     * }
     */
    public static void face(MemorySegment struct, byte fieldValue) {
        struct.set(face$LAYOUT, face$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

