// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3HullData {
 *     uint64_t version;
 *     uint64_t hash;
 *     b3AABB aabb;
 *     float surfaceArea;
 *     float volume;
 *     float innerRadius;
 *     b3Vec3 center;
 *     b3Matrix3 centralInertia;
 *     int32_t vertexCount;
 *     int32_t vertexOffset;
 *     int32_t pointOffset;
 *     int32_t edgeCount;
 *     int32_t edgeOffset;
 *     int32_t faceCount;
 *     int32_t planeOffset;
 *     int32_t faceOffset;
 *     int32_t soaVertexOffset;
 *     int32_t soaNormalOffset;
 *     int32_t byteCount;
 * }
 * }
 */
public class b3HullData {

    b3HullData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_LONG_LONG.withName("version"),
        Box3D.C_LONG_LONG.withName("hash"),
        b3AABB.layout().withName("aabb"),
        Box3D.C_FLOAT.withName("surfaceArea"),
        Box3D.C_FLOAT.withName("volume"),
        Box3D.C_FLOAT.withName("innerRadius"),
        b3Vec3.layout().withName("center"),
        b3Matrix3.layout().withName("centralInertia"),
        Box3D.C_INT.withName("vertexCount"),
        Box3D.C_INT.withName("vertexOffset"),
        Box3D.C_INT.withName("pointOffset"),
        Box3D.C_INT.withName("edgeCount"),
        Box3D.C_INT.withName("edgeOffset"),
        Box3D.C_INT.withName("faceCount"),
        Box3D.C_INT.withName("planeOffset"),
        Box3D.C_INT.withName("faceOffset"),
        Box3D.C_INT.withName("soaVertexOffset"),
        Box3D.C_INT.withName("soaNormalOffset"),
        Box3D.C_INT.withName("byteCount")
    ).withName("b3HullData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong version$LAYOUT = (OfLong)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static final OfLong version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static long version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t version
     * }
     */
    public static void version(MemorySegment struct, long fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfLong hash$LAYOUT = (OfLong)$LAYOUT.select(groupElement("hash"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static final OfLong hash$layout() {
        return hash$LAYOUT;
    }

    private static final long hash$OFFSET = $LAYOUT.byteOffset(groupElement("hash"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static final long hash$offset() {
        return hash$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static long hash(MemorySegment struct) {
        return struct.get(hash$LAYOUT, hash$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t hash
     * }
     */
    public static void hash(MemorySegment struct, long fieldValue) {
        struct.set(hash$LAYOUT, hash$OFFSET, fieldValue);
    }

    private static final GroupLayout aabb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("aabb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final GroupLayout aabb$layout() {
        return aabb$LAYOUT;
    }

    private static final long aabb$OFFSET = $LAYOUT.byteOffset(groupElement("aabb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final long aabb$offset() {
        return aabb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static MemorySegment aabb(MemorySegment struct) {
        return struct.asSlice(aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static void aabb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    private static final OfFloat surfaceArea$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("surfaceArea"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float surfaceArea
     * }
     */
    public static final OfFloat surfaceArea$layout() {
        return surfaceArea$LAYOUT;
    }

    private static final long surfaceArea$OFFSET = $LAYOUT.byteOffset(groupElement("surfaceArea"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float surfaceArea
     * }
     */
    public static final long surfaceArea$offset() {
        return surfaceArea$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float surfaceArea
     * }
     */
    public static float surfaceArea(MemorySegment struct) {
        return struct.get(surfaceArea$LAYOUT, surfaceArea$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float surfaceArea
     * }
     */
    public static void surfaceArea(MemorySegment struct, float fieldValue) {
        struct.set(surfaceArea$LAYOUT, surfaceArea$OFFSET, fieldValue);
    }

    private static final OfFloat volume$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("volume"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float volume
     * }
     */
    public static final OfFloat volume$layout() {
        return volume$LAYOUT;
    }

    private static final long volume$OFFSET = $LAYOUT.byteOffset(groupElement("volume"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float volume
     * }
     */
    public static final long volume$offset() {
        return volume$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float volume
     * }
     */
    public static float volume(MemorySegment struct) {
        return struct.get(volume$LAYOUT, volume$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float volume
     * }
     */
    public static void volume(MemorySegment struct, float fieldValue) {
        struct.set(volume$LAYOUT, volume$OFFSET, fieldValue);
    }

    private static final OfFloat innerRadius$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("innerRadius"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float innerRadius
     * }
     */
    public static final OfFloat innerRadius$layout() {
        return innerRadius$LAYOUT;
    }

    private static final long innerRadius$OFFSET = $LAYOUT.byteOffset(groupElement("innerRadius"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float innerRadius
     * }
     */
    public static final long innerRadius$offset() {
        return innerRadius$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float innerRadius
     * }
     */
    public static float innerRadius(MemorySegment struct) {
        return struct.get(innerRadius$LAYOUT, innerRadius$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float innerRadius
     * }
     */
    public static void innerRadius(MemorySegment struct, float fieldValue) {
        struct.set(innerRadius$LAYOUT, innerRadius$OFFSET, fieldValue);
    }

    private static final GroupLayout center$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("center"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 center
     * }
     */
    public static final GroupLayout center$layout() {
        return center$LAYOUT;
    }

    private static final long center$OFFSET = $LAYOUT.byteOffset(groupElement("center"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 center
     * }
     */
    public static final long center$offset() {
        return center$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 center
     * }
     */
    public static MemorySegment center(MemorySegment struct) {
        return struct.asSlice(center$OFFSET, center$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 center
     * }
     */
    public static void center(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, center$OFFSET, center$LAYOUT.byteSize());
    }

    private static final GroupLayout centralInertia$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("centralInertia"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Matrix3 centralInertia
     * }
     */
    public static final GroupLayout centralInertia$layout() {
        return centralInertia$LAYOUT;
    }

    private static final long centralInertia$OFFSET = $LAYOUT.byteOffset(groupElement("centralInertia"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Matrix3 centralInertia
     * }
     */
    public static final long centralInertia$offset() {
        return centralInertia$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Matrix3 centralInertia
     * }
     */
    public static MemorySegment centralInertia(MemorySegment struct) {
        return struct.asSlice(centralInertia$OFFSET, centralInertia$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Matrix3 centralInertia
     * }
     */
    public static void centralInertia(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, centralInertia$OFFSET, centralInertia$LAYOUT.byteSize());
    }

    private static final OfInt vertexCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vertexCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t vertexCount
     * }
     */
    public static final OfInt vertexCount$layout() {
        return vertexCount$LAYOUT;
    }

    private static final long vertexCount$OFFSET = $LAYOUT.byteOffset(groupElement("vertexCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t vertexCount
     * }
     */
    public static final long vertexCount$offset() {
        return vertexCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t vertexCount
     * }
     */
    public static int vertexCount(MemorySegment struct) {
        return struct.get(vertexCount$LAYOUT, vertexCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t vertexCount
     * }
     */
    public static void vertexCount(MemorySegment struct, int fieldValue) {
        struct.set(vertexCount$LAYOUT, vertexCount$OFFSET, fieldValue);
    }

    private static final OfInt vertexOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vertexOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t vertexOffset
     * }
     */
    public static final OfInt vertexOffset$layout() {
        return vertexOffset$LAYOUT;
    }

    private static final long vertexOffset$OFFSET = $LAYOUT.byteOffset(groupElement("vertexOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t vertexOffset
     * }
     */
    public static final long vertexOffset$offset() {
        return vertexOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t vertexOffset
     * }
     */
    public static int vertexOffset(MemorySegment struct) {
        return struct.get(vertexOffset$LAYOUT, vertexOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t vertexOffset
     * }
     */
    public static void vertexOffset(MemorySegment struct, int fieldValue) {
        struct.set(vertexOffset$LAYOUT, vertexOffset$OFFSET, fieldValue);
    }

    private static final OfInt pointOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pointOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t pointOffset
     * }
     */
    public static final OfInt pointOffset$layout() {
        return pointOffset$LAYOUT;
    }

    private static final long pointOffset$OFFSET = $LAYOUT.byteOffset(groupElement("pointOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t pointOffset
     * }
     */
    public static final long pointOffset$offset() {
        return pointOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t pointOffset
     * }
     */
    public static int pointOffset(MemorySegment struct) {
        return struct.get(pointOffset$LAYOUT, pointOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t pointOffset
     * }
     */
    public static void pointOffset(MemorySegment struct, int fieldValue) {
        struct.set(pointOffset$LAYOUT, pointOffset$OFFSET, fieldValue);
    }

    private static final OfInt edgeCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("edgeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t edgeCount
     * }
     */
    public static final OfInt edgeCount$layout() {
        return edgeCount$LAYOUT;
    }

    private static final long edgeCount$OFFSET = $LAYOUT.byteOffset(groupElement("edgeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t edgeCount
     * }
     */
    public static final long edgeCount$offset() {
        return edgeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t edgeCount
     * }
     */
    public static int edgeCount(MemorySegment struct) {
        return struct.get(edgeCount$LAYOUT, edgeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t edgeCount
     * }
     */
    public static void edgeCount(MemorySegment struct, int fieldValue) {
        struct.set(edgeCount$LAYOUT, edgeCount$OFFSET, fieldValue);
    }

    private static final OfInt edgeOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("edgeOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t edgeOffset
     * }
     */
    public static final OfInt edgeOffset$layout() {
        return edgeOffset$LAYOUT;
    }

    private static final long edgeOffset$OFFSET = $LAYOUT.byteOffset(groupElement("edgeOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t edgeOffset
     * }
     */
    public static final long edgeOffset$offset() {
        return edgeOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t edgeOffset
     * }
     */
    public static int edgeOffset(MemorySegment struct) {
        return struct.get(edgeOffset$LAYOUT, edgeOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t edgeOffset
     * }
     */
    public static void edgeOffset(MemorySegment struct, int fieldValue) {
        struct.set(edgeOffset$LAYOUT, edgeOffset$OFFSET, fieldValue);
    }

    private static final OfInt faceCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("faceCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t faceCount
     * }
     */
    public static final OfInt faceCount$layout() {
        return faceCount$LAYOUT;
    }

    private static final long faceCount$OFFSET = $LAYOUT.byteOffset(groupElement("faceCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t faceCount
     * }
     */
    public static final long faceCount$offset() {
        return faceCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t faceCount
     * }
     */
    public static int faceCount(MemorySegment struct) {
        return struct.get(faceCount$LAYOUT, faceCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t faceCount
     * }
     */
    public static void faceCount(MemorySegment struct, int fieldValue) {
        struct.set(faceCount$LAYOUT, faceCount$OFFSET, fieldValue);
    }

    private static final OfInt planeOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("planeOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t planeOffset
     * }
     */
    public static final OfInt planeOffset$layout() {
        return planeOffset$LAYOUT;
    }

    private static final long planeOffset$OFFSET = $LAYOUT.byteOffset(groupElement("planeOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t planeOffset
     * }
     */
    public static final long planeOffset$offset() {
        return planeOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t planeOffset
     * }
     */
    public static int planeOffset(MemorySegment struct) {
        return struct.get(planeOffset$LAYOUT, planeOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t planeOffset
     * }
     */
    public static void planeOffset(MemorySegment struct, int fieldValue) {
        struct.set(planeOffset$LAYOUT, planeOffset$OFFSET, fieldValue);
    }

    private static final OfInt faceOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("faceOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t faceOffset
     * }
     */
    public static final OfInt faceOffset$layout() {
        return faceOffset$LAYOUT;
    }

    private static final long faceOffset$OFFSET = $LAYOUT.byteOffset(groupElement("faceOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t faceOffset
     * }
     */
    public static final long faceOffset$offset() {
        return faceOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t faceOffset
     * }
     */
    public static int faceOffset(MemorySegment struct) {
        return struct.get(faceOffset$LAYOUT, faceOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t faceOffset
     * }
     */
    public static void faceOffset(MemorySegment struct, int fieldValue) {
        struct.set(faceOffset$LAYOUT, faceOffset$OFFSET, fieldValue);
    }

    private static final OfInt soaVertexOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("soaVertexOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t soaVertexOffset
     * }
     */
    public static final OfInt soaVertexOffset$layout() {
        return soaVertexOffset$LAYOUT;
    }

    private static final long soaVertexOffset$OFFSET = $LAYOUT.byteOffset(groupElement("soaVertexOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t soaVertexOffset
     * }
     */
    public static final long soaVertexOffset$offset() {
        return soaVertexOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t soaVertexOffset
     * }
     */
    public static int soaVertexOffset(MemorySegment struct) {
        return struct.get(soaVertexOffset$LAYOUT, soaVertexOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t soaVertexOffset
     * }
     */
    public static void soaVertexOffset(MemorySegment struct, int fieldValue) {
        struct.set(soaVertexOffset$LAYOUT, soaVertexOffset$OFFSET, fieldValue);
    }

    private static final OfInt soaNormalOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("soaNormalOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t soaNormalOffset
     * }
     */
    public static final OfInt soaNormalOffset$layout() {
        return soaNormalOffset$LAYOUT;
    }

    private static final long soaNormalOffset$OFFSET = $LAYOUT.byteOffset(groupElement("soaNormalOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t soaNormalOffset
     * }
     */
    public static final long soaNormalOffset$offset() {
        return soaNormalOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t soaNormalOffset
     * }
     */
    public static int soaNormalOffset(MemorySegment struct) {
        return struct.get(soaNormalOffset$LAYOUT, soaNormalOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t soaNormalOffset
     * }
     */
    public static void soaNormalOffset(MemorySegment struct, int fieldValue) {
        struct.set(soaNormalOffset$LAYOUT, soaNormalOffset$OFFSET, fieldValue);
    }

    private static final OfInt byteCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("byteCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t byteCount
     * }
     */
    public static final OfInt byteCount$layout() {
        return byteCount$LAYOUT;
    }

    private static final long byteCount$OFFSET = $LAYOUT.byteOffset(groupElement("byteCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t byteCount
     * }
     */
    public static final long byteCount$offset() {
        return byteCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t byteCount
     * }
     */
    public static int byteCount(MemorySegment struct) {
        return struct.get(byteCount$LAYOUT, byteCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t byteCount
     * }
     */
    public static void byteCount(MemorySegment struct, int fieldValue) {
        struct.set(byteCount$LAYOUT, byteCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

