// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3Manifold {
 *     b3ManifoldPoint points[4];
 *     b3Vec3 normal;
 *     float twistImpulse;
 *     b3Vec3 frictionImpulse;
 *     b3Vec3 rollingImpulse;
 *     int pointCount;
 * }
 * }
 */
public class b3Manifold {

    b3Manifold() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(4, b3ManifoldPoint.layout()).withName("points"),
        b3Vec3.layout().withName("normal"),
        Box3D.C_FLOAT.withName("twistImpulse"),
        b3Vec3.layout().withName("frictionImpulse"),
        b3Vec3.layout().withName("rollingImpulse"),
        Box3D.C_INT.withName("pointCount")
    ).withName("b3Manifold");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout points$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("points"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static final SequenceLayout points$layout() {
        return points$LAYOUT;
    }

    private static final long points$OFFSET = $LAYOUT.byteOffset(groupElement("points"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static final long points$offset() {
        return points$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static MemorySegment points(MemorySegment struct) {
        return struct.asSlice(points$OFFSET, points$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static void points(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, points$OFFSET, points$LAYOUT.byteSize());
    }

    private static long[] points$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static long[] points$dimensions() {
        return points$DIMS;
    }
    private static final MethodHandle points$ELEM_HANDLE = points$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static MemorySegment points(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)points$ELEM_HANDLE.invokeExact(struct, points$OFFSET, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * b3ManifoldPoint points[4]
     * }
     */
    public static void points(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, points(struct, index0), 0L, b3ManifoldPoint.layout().byteSize());
    }

    private static final GroupLayout normal$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("normal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 normal
     * }
     */
    public static final GroupLayout normal$layout() {
        return normal$LAYOUT;
    }

    private static final long normal$OFFSET = $LAYOUT.byteOffset(groupElement("normal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 normal
     * }
     */
    public static final long normal$offset() {
        return normal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 normal
     * }
     */
    public static MemorySegment normal(MemorySegment struct) {
        return struct.asSlice(normal$OFFSET, normal$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 normal
     * }
     */
    public static void normal(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, normal$OFFSET, normal$LAYOUT.byteSize());
    }

    private static final OfFloat twistImpulse$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("twistImpulse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float twistImpulse
     * }
     */
    public static final OfFloat twistImpulse$layout() {
        return twistImpulse$LAYOUT;
    }

    private static final long twistImpulse$OFFSET = $LAYOUT.byteOffset(groupElement("twistImpulse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float twistImpulse
     * }
     */
    public static final long twistImpulse$offset() {
        return twistImpulse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float twistImpulse
     * }
     */
    public static float twistImpulse(MemorySegment struct) {
        return struct.get(twistImpulse$LAYOUT, twistImpulse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float twistImpulse
     * }
     */
    public static void twistImpulse(MemorySegment struct, float fieldValue) {
        struct.set(twistImpulse$LAYOUT, twistImpulse$OFFSET, fieldValue);
    }

    private static final GroupLayout frictionImpulse$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("frictionImpulse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 frictionImpulse
     * }
     */
    public static final GroupLayout frictionImpulse$layout() {
        return frictionImpulse$LAYOUT;
    }

    private static final long frictionImpulse$OFFSET = $LAYOUT.byteOffset(groupElement("frictionImpulse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 frictionImpulse
     * }
     */
    public static final long frictionImpulse$offset() {
        return frictionImpulse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 frictionImpulse
     * }
     */
    public static MemorySegment frictionImpulse(MemorySegment struct) {
        return struct.asSlice(frictionImpulse$OFFSET, frictionImpulse$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 frictionImpulse
     * }
     */
    public static void frictionImpulse(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, frictionImpulse$OFFSET, frictionImpulse$LAYOUT.byteSize());
    }

    private static final GroupLayout rollingImpulse$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("rollingImpulse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 rollingImpulse
     * }
     */
    public static final GroupLayout rollingImpulse$layout() {
        return rollingImpulse$LAYOUT;
    }

    private static final long rollingImpulse$OFFSET = $LAYOUT.byteOffset(groupElement("rollingImpulse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 rollingImpulse
     * }
     */
    public static final long rollingImpulse$offset() {
        return rollingImpulse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 rollingImpulse
     * }
     */
    public static MemorySegment rollingImpulse(MemorySegment struct) {
        return struct.asSlice(rollingImpulse$OFFSET, rollingImpulse$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 rollingImpulse
     * }
     */
    public static void rollingImpulse(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rollingImpulse$OFFSET, rollingImpulse$LAYOUT.byteSize());
    }

    private static final OfInt pointCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pointCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int pointCount
     * }
     */
    public static final OfInt pointCount$layout() {
        return pointCount$LAYOUT;
    }

    private static final long pointCount$OFFSET = $LAYOUT.byteOffset(groupElement("pointCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int pointCount
     * }
     */
    public static final long pointCount$offset() {
        return pointCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pointCount
     * }
     */
    public static int pointCount(MemorySegment struct) {
        return struct.get(pointCount$LAYOUT, pointCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pointCount
     * }
     */
    public static void pointCount(MemorySegment struct, int fieldValue) {
        struct.set(pointCount$LAYOUT, pointCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

