// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3MeshTriangle {
 *     int32_t index1;
 *     int32_t index2;
 *     int32_t index3;
 * }
 * }
 */
public class b3MeshTriangle {

    b3MeshTriangle() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_INT.withName("index1"),
        Box3D.C_INT.withName("index2"),
        Box3D.C_INT.withName("index3")
    ).withName("b3MeshTriangle");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt index1$LAYOUT = (OfInt)$LAYOUT.select(groupElement("index1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t index1
     * }
     */
    public static final OfInt index1$layout() {
        return index1$LAYOUT;
    }

    private static final long index1$OFFSET = $LAYOUT.byteOffset(groupElement("index1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t index1
     * }
     */
    public static final long index1$offset() {
        return index1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t index1
     * }
     */
    public static int index1(MemorySegment struct) {
        return struct.get(index1$LAYOUT, index1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t index1
     * }
     */
    public static void index1(MemorySegment struct, int fieldValue) {
        struct.set(index1$LAYOUT, index1$OFFSET, fieldValue);
    }

    private static final OfInt index2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("index2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t index2
     * }
     */
    public static final OfInt index2$layout() {
        return index2$LAYOUT;
    }

    private static final long index2$OFFSET = $LAYOUT.byteOffset(groupElement("index2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t index2
     * }
     */
    public static final long index2$offset() {
        return index2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t index2
     * }
     */
    public static int index2(MemorySegment struct) {
        return struct.get(index2$LAYOUT, index2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t index2
     * }
     */
    public static void index2(MemorySegment struct, int fieldValue) {
        struct.set(index2$LAYOUT, index2$OFFSET, fieldValue);
    }

    private static final OfInt index3$LAYOUT = (OfInt)$LAYOUT.select(groupElement("index3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t index3
     * }
     */
    public static final OfInt index3$layout() {
        return index3$LAYOUT;
    }

    private static final long index3$OFFSET = $LAYOUT.byteOffset(groupElement("index3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t index3
     * }
     */
    public static final long index3$offset() {
        return index3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t index3
     * }
     */
    public static int index3(MemorySegment struct) {
        return struct.get(index3$LAYOUT, index3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t index3
     * }
     */
    public static void index3(MemorySegment struct, int fieldValue) {
        struct.set(index3$LAYOUT, index3$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

