// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3PlaneResult {
 *     b3Plane plane;
 *     b3Vec3 point;
 *     int triangleIndex;
 *     int childIndex;
 *     int materialIndex;
 * }
 * }
 */
public class b3PlaneResult {

    b3PlaneResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Plane.layout().withName("plane"),
        b3Vec3.layout().withName("point"),
        Box3D.C_INT.withName("triangleIndex"),
        Box3D.C_INT.withName("childIndex"),
        Box3D.C_INT.withName("materialIndex")
    ).withName("b3PlaneResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout plane$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("plane"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static final GroupLayout plane$layout() {
        return plane$LAYOUT;
    }

    private static final long plane$OFFSET = $LAYOUT.byteOffset(groupElement("plane"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static final long plane$offset() {
        return plane$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static MemorySegment plane(MemorySegment struct) {
        return struct.asSlice(plane$OFFSET, plane$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Plane plane
     * }
     */
    public static void plane(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, plane$OFFSET, plane$LAYOUT.byteSize());
    }

    private static final GroupLayout point$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("point"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 point
     * }
     */
    public static final GroupLayout point$layout() {
        return point$LAYOUT;
    }

    private static final long point$OFFSET = $LAYOUT.byteOffset(groupElement("point"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 point
     * }
     */
    public static final long point$offset() {
        return point$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 point
     * }
     */
    public static MemorySegment point(MemorySegment struct) {
        return struct.asSlice(point$OFFSET, point$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 point
     * }
     */
    public static void point(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, point$OFFSET, point$LAYOUT.byteSize());
    }

    private static final OfInt triangleIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("triangleIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int triangleIndex
     * }
     */
    public static final OfInt triangleIndex$layout() {
        return triangleIndex$LAYOUT;
    }

    private static final long triangleIndex$OFFSET = $LAYOUT.byteOffset(groupElement("triangleIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int triangleIndex
     * }
     */
    public static final long triangleIndex$offset() {
        return triangleIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int triangleIndex
     * }
     */
    public static int triangleIndex(MemorySegment struct) {
        return struct.get(triangleIndex$LAYOUT, triangleIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int triangleIndex
     * }
     */
    public static void triangleIndex(MemorySegment struct, int fieldValue) {
        struct.set(triangleIndex$LAYOUT, triangleIndex$OFFSET, fieldValue);
    }

    private static final OfInt childIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("childIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int childIndex
     * }
     */
    public static final OfInt childIndex$layout() {
        return childIndex$LAYOUT;
    }

    private static final long childIndex$OFFSET = $LAYOUT.byteOffset(groupElement("childIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int childIndex
     * }
     */
    public static final long childIndex$offset() {
        return childIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int childIndex
     * }
     */
    public static int childIndex(MemorySegment struct) {
        return struct.get(childIndex$LAYOUT, childIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int childIndex
     * }
     */
    public static void childIndex(MemorySegment struct, int fieldValue) {
        struct.set(childIndex$LAYOUT, childIndex$OFFSET, fieldValue);
    }

    private static final OfInt materialIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("materialIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static final OfInt materialIndex$layout() {
        return materialIndex$LAYOUT;
    }

    private static final long materialIndex$OFFSET = $LAYOUT.byteOffset(groupElement("materialIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static final long materialIndex$offset() {
        return materialIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static int materialIndex(MemorySegment struct) {
        return struct.get(materialIndex$LAYOUT, materialIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int materialIndex
     * }
     */
    public static void materialIndex(MemorySegment struct, int fieldValue) {
        struct.set(materialIndex$LAYOUT, materialIndex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

