// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3RevoluteJointDef {
 *     b3JointDef base;
 *     float targetAngle;
 *     _Bool enableSpring;
 *     float hertz;
 *     float dampingRatio;
 *     _Bool enableLimit;
 *     float lowerAngle;
 *     float upperAngle;
 *     _Bool enableMotor;
 *     float maxMotorTorque;
 *     float motorSpeed;
 * }
 * }
 */
public class b3RevoluteJointDef {

    b3RevoluteJointDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3JointDef.layout().withName("base"),
        Box3D.C_FLOAT.withName("targetAngle"),
        Box3D.C_BOOL.withName("enableSpring"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("hertz"),
        Box3D.C_FLOAT.withName("dampingRatio"),
        Box3D.C_BOOL.withName("enableLimit"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("lowerAngle"),
        Box3D.C_FLOAT.withName("upperAngle"),
        Box3D.C_BOOL.withName("enableMotor"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("maxMotorTorque"),
        Box3D.C_FLOAT.withName("motorSpeed")
    ).withName("b3RevoluteJointDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    private static final OfFloat targetAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("targetAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float targetAngle
     * }
     */
    public static final OfFloat targetAngle$layout() {
        return targetAngle$LAYOUT;
    }

    private static final long targetAngle$OFFSET = $LAYOUT.byteOffset(groupElement("targetAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float targetAngle
     * }
     */
    public static final long targetAngle$offset() {
        return targetAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float targetAngle
     * }
     */
    public static float targetAngle(MemorySegment struct) {
        return struct.get(targetAngle$LAYOUT, targetAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float targetAngle
     * }
     */
    public static void targetAngle(MemorySegment struct, float fieldValue) {
        struct.set(targetAngle$LAYOUT, targetAngle$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSpring$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSpring"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static final OfBoolean enableSpring$layout() {
        return enableSpring$LAYOUT;
    }

    private static final long enableSpring$OFFSET = $LAYOUT.byteOffset(groupElement("enableSpring"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static final long enableSpring$offset() {
        return enableSpring$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static boolean enableSpring(MemorySegment struct) {
        return struct.get(enableSpring$LAYOUT, enableSpring$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static void enableSpring(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSpring$LAYOUT, enableSpring$OFFSET, fieldValue);
    }

    private static final OfFloat hertz$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("hertz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static final OfFloat hertz$layout() {
        return hertz$LAYOUT;
    }

    private static final long hertz$OFFSET = $LAYOUT.byteOffset(groupElement("hertz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static final long hertz$offset() {
        return hertz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static float hertz(MemorySegment struct) {
        return struct.get(hertz$LAYOUT, hertz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static void hertz(MemorySegment struct, float fieldValue) {
        struct.set(hertz$LAYOUT, hertz$OFFSET, fieldValue);
    }

    private static final OfFloat dampingRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("dampingRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static final OfFloat dampingRatio$layout() {
        return dampingRatio$LAYOUT;
    }

    private static final long dampingRatio$OFFSET = $LAYOUT.byteOffset(groupElement("dampingRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static final long dampingRatio$offset() {
        return dampingRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static float dampingRatio(MemorySegment struct) {
        return struct.get(dampingRatio$LAYOUT, dampingRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static void dampingRatio(MemorySegment struct, float fieldValue) {
        struct.set(dampingRatio$LAYOUT, dampingRatio$OFFSET, fieldValue);
    }

    private static final OfBoolean enableLimit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableLimit
     * }
     */
    public static final OfBoolean enableLimit$layout() {
        return enableLimit$LAYOUT;
    }

    private static final long enableLimit$OFFSET = $LAYOUT.byteOffset(groupElement("enableLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableLimit
     * }
     */
    public static final long enableLimit$offset() {
        return enableLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableLimit
     * }
     */
    public static boolean enableLimit(MemorySegment struct) {
        return struct.get(enableLimit$LAYOUT, enableLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableLimit
     * }
     */
    public static void enableLimit(MemorySegment struct, boolean fieldValue) {
        struct.set(enableLimit$LAYOUT, enableLimit$OFFSET, fieldValue);
    }

    private static final OfFloat lowerAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("lowerAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float lowerAngle
     * }
     */
    public static final OfFloat lowerAngle$layout() {
        return lowerAngle$LAYOUT;
    }

    private static final long lowerAngle$OFFSET = $LAYOUT.byteOffset(groupElement("lowerAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float lowerAngle
     * }
     */
    public static final long lowerAngle$offset() {
        return lowerAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float lowerAngle
     * }
     */
    public static float lowerAngle(MemorySegment struct) {
        return struct.get(lowerAngle$LAYOUT, lowerAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float lowerAngle
     * }
     */
    public static void lowerAngle(MemorySegment struct, float fieldValue) {
        struct.set(lowerAngle$LAYOUT, lowerAngle$OFFSET, fieldValue);
    }

    private static final OfFloat upperAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("upperAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float upperAngle
     * }
     */
    public static final OfFloat upperAngle$layout() {
        return upperAngle$LAYOUT;
    }

    private static final long upperAngle$OFFSET = $LAYOUT.byteOffset(groupElement("upperAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float upperAngle
     * }
     */
    public static final long upperAngle$offset() {
        return upperAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float upperAngle
     * }
     */
    public static float upperAngle(MemorySegment struct) {
        return struct.get(upperAngle$LAYOUT, upperAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float upperAngle
     * }
     */
    public static void upperAngle(MemorySegment struct, float fieldValue) {
        struct.set(upperAngle$LAYOUT, upperAngle$OFFSET, fieldValue);
    }

    private static final OfBoolean enableMotor$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableMotor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static final OfBoolean enableMotor$layout() {
        return enableMotor$LAYOUT;
    }

    private static final long enableMotor$OFFSET = $LAYOUT.byteOffset(groupElement("enableMotor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static final long enableMotor$offset() {
        return enableMotor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static boolean enableMotor(MemorySegment struct) {
        return struct.get(enableMotor$LAYOUT, enableMotor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static void enableMotor(MemorySegment struct, boolean fieldValue) {
        struct.set(enableMotor$LAYOUT, enableMotor$OFFSET, fieldValue);
    }

    private static final OfFloat maxMotorTorque$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxMotorTorque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static final OfFloat maxMotorTorque$layout() {
        return maxMotorTorque$LAYOUT;
    }

    private static final long maxMotorTorque$OFFSET = $LAYOUT.byteOffset(groupElement("maxMotorTorque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static final long maxMotorTorque$offset() {
        return maxMotorTorque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static float maxMotorTorque(MemorySegment struct) {
        return struct.get(maxMotorTorque$LAYOUT, maxMotorTorque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static void maxMotorTorque(MemorySegment struct, float fieldValue) {
        struct.set(maxMotorTorque$LAYOUT, maxMotorTorque$OFFSET, fieldValue);
    }

    private static final OfFloat motorSpeed$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("motorSpeed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float motorSpeed
     * }
     */
    public static final OfFloat motorSpeed$layout() {
        return motorSpeed$LAYOUT;
    }

    private static final long motorSpeed$OFFSET = $LAYOUT.byteOffset(groupElement("motorSpeed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float motorSpeed
     * }
     */
    public static final long motorSpeed$offset() {
        return motorSpeed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float motorSpeed
     * }
     */
    public static float motorSpeed(MemorySegment struct) {
        return struct.get(motorSpeed$LAYOUT, motorSpeed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float motorSpeed
     * }
     */
    public static void motorSpeed(MemorySegment struct, float fieldValue) {
        struct.set(motorSpeed$LAYOUT, motorSpeed$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

