// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3RecQueryInfo {
 *     b3RecQueryType type;
 *     b3QueryFilter filter;
 *     b3AABB aabb;
 *     b3Pos origin;
 *     b3Vec3 translation;
 *     int hitCount;
 *     uint64_t key;
 *     uint64_t id;
 *     const char *name;
 * }
 * }
 */
public class b3RecQueryInfo {

    b3RecQueryInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        b3QueryFilter.layout().withName("filter"),
        b3AABB.layout().withName("aabb"),
        b3Vec3.layout().withName("origin"),
        b3Vec3.layout().withName("translation"),
        Box3D.C_INT.withName("hitCount"),
        MemoryLayout.paddingLayout(4),
        Box3D.C_LONG_LONG.withName("key"),
        Box3D.C_LONG_LONG.withName("id"),
        Box3D.C_POINTER.withName("name")
    ).withName("b3RecQueryInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3RecQueryType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3RecQueryType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3RecQueryType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3RecQueryType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final GroupLayout filter$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3QueryFilter filter
     * }
     */
    public static final GroupLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3QueryFilter filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3QueryFilter filter
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.asSlice(filter$OFFSET, filter$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3QueryFilter filter
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, filter$OFFSET, filter$LAYOUT.byteSize());
    }

    private static final GroupLayout aabb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("aabb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final GroupLayout aabb$layout() {
        return aabb$LAYOUT;
    }

    private static final long aabb$OFFSET = $LAYOUT.byteOffset(groupElement("aabb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final long aabb$offset() {
        return aabb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static MemorySegment aabb(MemorySegment struct) {
        return struct.asSlice(aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static void aabb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    private static final GroupLayout origin$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("origin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Pos origin
     * }
     */
    public static final GroupLayout origin$layout() {
        return origin$LAYOUT;
    }

    private static final long origin$OFFSET = $LAYOUT.byteOffset(groupElement("origin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Pos origin
     * }
     */
    public static final long origin$offset() {
        return origin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Pos origin
     * }
     */
    public static MemorySegment origin(MemorySegment struct) {
        return struct.asSlice(origin$OFFSET, origin$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Pos origin
     * }
     */
    public static void origin(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, origin$OFFSET, origin$LAYOUT.byteSize());
    }

    private static final GroupLayout translation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("translation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final GroupLayout translation$layout() {
        return translation$LAYOUT;
    }

    private static final long translation$OFFSET = $LAYOUT.byteOffset(groupElement("translation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final long translation$offset() {
        return translation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static MemorySegment translation(MemorySegment struct) {
        return struct.asSlice(translation$OFFSET, translation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static void translation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, translation$OFFSET, translation$LAYOUT.byteSize());
    }

    private static final OfInt hitCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hitCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int hitCount
     * }
     */
    public static final OfInt hitCount$layout() {
        return hitCount$LAYOUT;
    }

    private static final long hitCount$OFFSET = $LAYOUT.byteOffset(groupElement("hitCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int hitCount
     * }
     */
    public static final long hitCount$offset() {
        return hitCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int hitCount
     * }
     */
    public static int hitCount(MemorySegment struct) {
        return struct.get(hitCount$LAYOUT, hitCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int hitCount
     * }
     */
    public static void hitCount(MemorySegment struct, int fieldValue) {
        struct.set(hitCount$LAYOUT, hitCount$OFFSET, fieldValue);
    }

    private static final OfLong key$LAYOUT = (OfLong)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t key
     * }
     */
    public static final OfLong key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t key
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t key
     * }
     */
    public static long key(MemorySegment struct) {
        return struct.get(key$LAYOUT, key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t key
     * }
     */
    public static void key(MemorySegment struct, long fieldValue) {
        struct.set(key$LAYOUT, key$OFFSET, fieldValue);
    }

    private static final OfLong id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t id
     * }
     */
    public static final OfLong id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t id
     * }
     */
    public static long id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t id
     * }
     */
    public static void id(MemorySegment struct, long fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

