// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3SegmentDistanceResult {
 *     b3Vec3 point1;
 *     float fraction1;
 *     b3Vec3 point2;
 *     float fraction2;
 * }
 * }
 */
public class b3SegmentDistanceResult {

    b3SegmentDistanceResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Vec3.layout().withName("point1"),
        Box3D.C_FLOAT.withName("fraction1"),
        b3Vec3.layout().withName("point2"),
        Box3D.C_FLOAT.withName("fraction2")
    ).withName("b3SegmentDistanceResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout point1$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("point1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 point1
     * }
     */
    public static final GroupLayout point1$layout() {
        return point1$LAYOUT;
    }

    private static final long point1$OFFSET = $LAYOUT.byteOffset(groupElement("point1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 point1
     * }
     */
    public static final long point1$offset() {
        return point1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 point1
     * }
     */
    public static MemorySegment point1(MemorySegment struct) {
        return struct.asSlice(point1$OFFSET, point1$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 point1
     * }
     */
    public static void point1(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, point1$OFFSET, point1$LAYOUT.byteSize());
    }

    private static final OfFloat fraction1$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("fraction1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float fraction1
     * }
     */
    public static final OfFloat fraction1$layout() {
        return fraction1$LAYOUT;
    }

    private static final long fraction1$OFFSET = $LAYOUT.byteOffset(groupElement("fraction1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float fraction1
     * }
     */
    public static final long fraction1$offset() {
        return fraction1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction1
     * }
     */
    public static float fraction1(MemorySegment struct) {
        return struct.get(fraction1$LAYOUT, fraction1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction1
     * }
     */
    public static void fraction1(MemorySegment struct, float fieldValue) {
        struct.set(fraction1$LAYOUT, fraction1$OFFSET, fieldValue);
    }

    private static final GroupLayout point2$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("point2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 point2
     * }
     */
    public static final GroupLayout point2$layout() {
        return point2$LAYOUT;
    }

    private static final long point2$OFFSET = $LAYOUT.byteOffset(groupElement("point2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 point2
     * }
     */
    public static final long point2$offset() {
        return point2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 point2
     * }
     */
    public static MemorySegment point2(MemorySegment struct) {
        return struct.asSlice(point2$OFFSET, point2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 point2
     * }
     */
    public static void point2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, point2$OFFSET, point2$LAYOUT.byteSize());
    }

    private static final OfFloat fraction2$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("fraction2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float fraction2
     * }
     */
    public static final OfFloat fraction2$layout() {
        return fraction2$LAYOUT;
    }

    private static final long fraction2$OFFSET = $LAYOUT.byteOffset(groupElement("fraction2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float fraction2
     * }
     */
    public static final long fraction2$offset() {
        return fraction2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction2
     * }
     */
    public static float fraction2(MemorySegment struct) {
        return struct.get(fraction2$LAYOUT, fraction2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction2
     * }
     */
    public static void fraction2(MemorySegment struct, float fieldValue) {
        struct.set(fraction2$LAYOUT, fraction2$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

