// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3SensorEvents {
 *     b3SensorBeginTouchEvent *beginEvents;
 *     b3SensorEndTouchEvent *endEvents;
 *     int beginCount;
 *     int endCount;
 * }
 * }
 */
public class b3SensorEvents {

    b3SensorEvents() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_POINTER.withName("beginEvents"),
        Box3D.C_POINTER.withName("endEvents"),
        Box3D.C_INT.withName("beginCount"),
        Box3D.C_INT.withName("endCount")
    ).withName("b3SensorEvents");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout beginEvents$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("beginEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3SensorBeginTouchEvent *beginEvents
     * }
     */
    public static final AddressLayout beginEvents$layout() {
        return beginEvents$LAYOUT;
    }

    private static final long beginEvents$OFFSET = $LAYOUT.byteOffset(groupElement("beginEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3SensorBeginTouchEvent *beginEvents
     * }
     */
    public static final long beginEvents$offset() {
        return beginEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3SensorBeginTouchEvent *beginEvents
     * }
     */
    public static MemorySegment beginEvents(MemorySegment struct) {
        return struct.get(beginEvents$LAYOUT, beginEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3SensorBeginTouchEvent *beginEvents
     * }
     */
    public static void beginEvents(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(beginEvents$LAYOUT, beginEvents$OFFSET, fieldValue);
    }

    private static final AddressLayout endEvents$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("endEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3SensorEndTouchEvent *endEvents
     * }
     */
    public static final AddressLayout endEvents$layout() {
        return endEvents$LAYOUT;
    }

    private static final long endEvents$OFFSET = $LAYOUT.byteOffset(groupElement("endEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3SensorEndTouchEvent *endEvents
     * }
     */
    public static final long endEvents$offset() {
        return endEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3SensorEndTouchEvent *endEvents
     * }
     */
    public static MemorySegment endEvents(MemorySegment struct) {
        return struct.get(endEvents$LAYOUT, endEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3SensorEndTouchEvent *endEvents
     * }
     */
    public static void endEvents(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(endEvents$LAYOUT, endEvents$OFFSET, fieldValue);
    }

    private static final OfInt beginCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("beginCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int beginCount
     * }
     */
    public static final OfInt beginCount$layout() {
        return beginCount$LAYOUT;
    }

    private static final long beginCount$OFFSET = $LAYOUT.byteOffset(groupElement("beginCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int beginCount
     * }
     */
    public static final long beginCount$offset() {
        return beginCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int beginCount
     * }
     */
    public static int beginCount(MemorySegment struct) {
        return struct.get(beginCount$LAYOUT, beginCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int beginCount
     * }
     */
    public static void beginCount(MemorySegment struct, int fieldValue) {
        struct.set(beginCount$LAYOUT, beginCount$OFFSET, fieldValue);
    }

    private static final OfInt endCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("endCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int endCount
     * }
     */
    public static final OfInt endCount$layout() {
        return endCount$LAYOUT;
    }

    private static final long endCount$OFFSET = $LAYOUT.byteOffset(groupElement("endCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int endCount
     * }
     */
    public static final long endCount$offset() {
        return endCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int endCount
     * }
     */
    public static int endCount(MemorySegment struct) {
        return struct.get(endCount$LAYOUT, endCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int endCount
     * }
     */
    public static void endCount(MemorySegment struct, int fieldValue) {
        struct.set(endCount$LAYOUT, endCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

