// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3ShapeCastInput {
 *     b3ShapeProxy proxy;
 *     b3Vec3 translation;
 *     float maxFraction;
 *     _Bool canEncroach;
 * }
 * }
 */
public class b3ShapeCastInput {

    b3ShapeCastInput() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3ShapeProxy.layout().withName("proxy"),
        b3Vec3.layout().withName("translation"),
        Box3D.C_FLOAT.withName("maxFraction"),
        Box3D.C_BOOL.withName("canEncroach"),
        MemoryLayout.paddingLayout(7)
    ).withName("b3ShapeCastInput");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout proxy$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxy
     * }
     */
    public static final GroupLayout proxy$layout() {
        return proxy$LAYOUT;
    }

    private static final long proxy$OFFSET = $LAYOUT.byteOffset(groupElement("proxy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxy
     * }
     */
    public static final long proxy$offset() {
        return proxy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxy
     * }
     */
    public static MemorySegment proxy(MemorySegment struct) {
        return struct.asSlice(proxy$OFFSET, proxy$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxy
     * }
     */
    public static void proxy(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxy$OFFSET, proxy$LAYOUT.byteSize());
    }

    private static final GroupLayout translation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("translation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final GroupLayout translation$layout() {
        return translation$LAYOUT;
    }

    private static final long translation$OFFSET = $LAYOUT.byteOffset(groupElement("translation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static final long translation$offset() {
        return translation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static MemorySegment translation(MemorySegment struct) {
        return struct.asSlice(translation$OFFSET, translation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 translation
     * }
     */
    public static void translation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, translation$OFFSET, translation$LAYOUT.byteSize());
    }

    private static final OfFloat maxFraction$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxFraction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final OfFloat maxFraction$layout() {
        return maxFraction$LAYOUT;
    }

    private static final long maxFraction$OFFSET = $LAYOUT.byteOffset(groupElement("maxFraction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final long maxFraction$offset() {
        return maxFraction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static float maxFraction(MemorySegment struct) {
        return struct.get(maxFraction$LAYOUT, maxFraction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static void maxFraction(MemorySegment struct, float fieldValue) {
        struct.set(maxFraction$LAYOUT, maxFraction$OFFSET, fieldValue);
    }

    private static final OfBoolean canEncroach$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("canEncroach"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static final OfBoolean canEncroach$layout() {
        return canEncroach$LAYOUT;
    }

    private static final long canEncroach$OFFSET = $LAYOUT.byteOffset(groupElement("canEncroach"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static final long canEncroach$offset() {
        return canEncroach$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static boolean canEncroach(MemorySegment struct) {
        return struct.get(canEncroach$LAYOUT, canEncroach$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static void canEncroach(MemorySegment struct, boolean fieldValue) {
        struct.set(canEncroach$LAYOUT, canEncroach$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

