// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3ShapeCastPairInput {
 *     b3ShapeProxy proxyA;
 *     b3ShapeProxy proxyB;
 *     b3Transform transform;
 *     b3Vec3 translationB;
 *     float maxFraction;
 *     _Bool canEncroach;
 * }
 * }
 */
public class b3ShapeCastPairInput {

    b3ShapeCastPairInput() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3ShapeProxy.layout().withName("proxyA"),
        b3ShapeProxy.layout().withName("proxyB"),
        b3Transform.layout().withName("transform"),
        b3Vec3.layout().withName("translationB"),
        Box3D.C_FLOAT.withName("maxFraction"),
        Box3D.C_BOOL.withName("canEncroach"),
        MemoryLayout.paddingLayout(3)
    ).withName("b3ShapeCastPairInput");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout proxyA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static final GroupLayout proxyA$layout() {
        return proxyA$LAYOUT;
    }

    private static final long proxyA$OFFSET = $LAYOUT.byteOffset(groupElement("proxyA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static final long proxyA$offset() {
        return proxyA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static MemorySegment proxyA(MemorySegment struct) {
        return struct.asSlice(proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyA
     * }
     */
    public static void proxyA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    private static final GroupLayout proxyB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static final GroupLayout proxyB$layout() {
        return proxyB$LAYOUT;
    }

    private static final long proxyB$OFFSET = $LAYOUT.byteOffset(groupElement("proxyB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static final long proxyB$offset() {
        return proxyB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static MemorySegment proxyB(MemorySegment struct) {
        return struct.asSlice(proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3ShapeProxy proxyB
     * }
     */
    public static void proxyB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    private static final GroupLayout transform$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transform"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final GroupLayout transform$layout() {
        return transform$LAYOUT;
    }

    private static final long transform$OFFSET = $LAYOUT.byteOffset(groupElement("transform"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static final long transform$offset() {
        return transform$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static MemorySegment transform(MemorySegment struct) {
        return struct.asSlice(transform$OFFSET, transform$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Transform transform
     * }
     */
    public static void transform(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transform$OFFSET, transform$LAYOUT.byteSize());
    }

    private static final GroupLayout translationB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("translationB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 translationB
     * }
     */
    public static final GroupLayout translationB$layout() {
        return translationB$LAYOUT;
    }

    private static final long translationB$OFFSET = $LAYOUT.byteOffset(groupElement("translationB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 translationB
     * }
     */
    public static final long translationB$offset() {
        return translationB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 translationB
     * }
     */
    public static MemorySegment translationB(MemorySegment struct) {
        return struct.asSlice(translationB$OFFSET, translationB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 translationB
     * }
     */
    public static void translationB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, translationB$OFFSET, translationB$LAYOUT.byteSize());
    }

    private static final OfFloat maxFraction$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxFraction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final OfFloat maxFraction$layout() {
        return maxFraction$LAYOUT;
    }

    private static final long maxFraction$OFFSET = $LAYOUT.byteOffset(groupElement("maxFraction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static final long maxFraction$offset() {
        return maxFraction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static float maxFraction(MemorySegment struct) {
        return struct.get(maxFraction$LAYOUT, maxFraction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxFraction
     * }
     */
    public static void maxFraction(MemorySegment struct, float fieldValue) {
        struct.set(maxFraction$LAYOUT, maxFraction$OFFSET, fieldValue);
    }

    private static final OfBoolean canEncroach$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("canEncroach"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static final OfBoolean canEncroach$layout() {
        return canEncroach$LAYOUT;
    }

    private static final long canEncroach$OFFSET = $LAYOUT.byteOffset(groupElement("canEncroach"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static final long canEncroach$offset() {
        return canEncroach$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static boolean canEncroach(MemorySegment struct) {
        return struct.get(canEncroach$LAYOUT, canEncroach$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool canEncroach
     * }
     */
    public static void canEncroach(MemorySegment struct, boolean fieldValue) {
        struct.set(canEncroach$LAYOUT, canEncroach$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

