// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3ShapeDef {
 *     const char *name;
 *     void *userData;
 *     b3SurfaceMaterial *materials;
 *     int materialCount;
 *     b3SurfaceMaterial baseMaterial;
 *     float density;
 *     float explosionScale;
 *     b3Filter filter;
 *     _Bool enableCustomFiltering;
 *     _Bool isSensor;
 *     _Bool enableSensorEvents;
 *     _Bool enableContactEvents;
 *     _Bool enableHitEvents;
 *     _Bool enablePreSolveEvents;
 *     _Bool invokeContactCreation;
 *     _Bool updateBodyMass;
 *     _Bool enableSpeculativeContact;
 *     int internalValue;
 * }
 * }
 */
public class b3ShapeDef {

    b3ShapeDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_POINTER.withName("name"),
        Box3D.C_POINTER.withName("userData"),
        Box3D.C_POINTER.withName("materials"),
        Box3D.C_INT.withName("materialCount"),
        MemoryLayout.paddingLayout(4),
        b3SurfaceMaterial.layout().withName("baseMaterial"),
        Box3D.C_FLOAT.withName("density"),
        Box3D.C_FLOAT.withName("explosionScale"),
        b3Filter.layout().withName("filter"),
        Box3D.C_BOOL.withName("enableCustomFiltering"),
        Box3D.C_BOOL.withName("isSensor"),
        Box3D.C_BOOL.withName("enableSensorEvents"),
        Box3D.C_BOOL.withName("enableContactEvents"),
        Box3D.C_BOOL.withName("enableHitEvents"),
        Box3D.C_BOOL.withName("enablePreSolveEvents"),
        Box3D.C_BOOL.withName("invokeContactCreation"),
        Box3D.C_BOOL.withName("updateBodyMass"),
        Box3D.C_BOOL.withName("enableSpeculativeContact"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_INT.withName("internalValue")
    ).withName("b3ShapeDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout userData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static final AddressLayout userData$layout() {
        return userData$LAYOUT;
    }

    private static final long userData$OFFSET = $LAYOUT.byteOffset(groupElement("userData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static final long userData$offset() {
        return userData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static MemorySegment userData(MemorySegment struct) {
        return struct.get(userData$LAYOUT, userData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static void userData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userData$LAYOUT, userData$OFFSET, fieldValue);
    }

    private static final AddressLayout materials$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("materials"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial *materials
     * }
     */
    public static final AddressLayout materials$layout() {
        return materials$LAYOUT;
    }

    private static final long materials$OFFSET = $LAYOUT.byteOffset(groupElement("materials"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial *materials
     * }
     */
    public static final long materials$offset() {
        return materials$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial *materials
     * }
     */
    public static MemorySegment materials(MemorySegment struct) {
        return struct.get(materials$LAYOUT, materials$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial *materials
     * }
     */
    public static void materials(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(materials$LAYOUT, materials$OFFSET, fieldValue);
    }

    private static final OfInt materialCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("materialCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int materialCount
     * }
     */
    public static final OfInt materialCount$layout() {
        return materialCount$LAYOUT;
    }

    private static final long materialCount$OFFSET = $LAYOUT.byteOffset(groupElement("materialCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int materialCount
     * }
     */
    public static final long materialCount$offset() {
        return materialCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int materialCount
     * }
     */
    public static int materialCount(MemorySegment struct) {
        return struct.get(materialCount$LAYOUT, materialCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int materialCount
     * }
     */
    public static void materialCount(MemorySegment struct, int fieldValue) {
        struct.set(materialCount$LAYOUT, materialCount$OFFSET, fieldValue);
    }

    private static final GroupLayout baseMaterial$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("baseMaterial"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial baseMaterial
     * }
     */
    public static final GroupLayout baseMaterial$layout() {
        return baseMaterial$LAYOUT;
    }

    private static final long baseMaterial$OFFSET = $LAYOUT.byteOffset(groupElement("baseMaterial"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial baseMaterial
     * }
     */
    public static final long baseMaterial$offset() {
        return baseMaterial$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial baseMaterial
     * }
     */
    public static MemorySegment baseMaterial(MemorySegment struct) {
        return struct.asSlice(baseMaterial$OFFSET, baseMaterial$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3SurfaceMaterial baseMaterial
     * }
     */
    public static void baseMaterial(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, baseMaterial$OFFSET, baseMaterial$LAYOUT.byteSize());
    }

    private static final OfFloat density$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("density"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float density
     * }
     */
    public static final OfFloat density$layout() {
        return density$LAYOUT;
    }

    private static final long density$OFFSET = $LAYOUT.byteOffset(groupElement("density"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float density
     * }
     */
    public static final long density$offset() {
        return density$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float density
     * }
     */
    public static float density(MemorySegment struct) {
        return struct.get(density$LAYOUT, density$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float density
     * }
     */
    public static void density(MemorySegment struct, float fieldValue) {
        struct.set(density$LAYOUT, density$OFFSET, fieldValue);
    }

    private static final OfFloat explosionScale$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("explosionScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float explosionScale
     * }
     */
    public static final OfFloat explosionScale$layout() {
        return explosionScale$LAYOUT;
    }

    private static final long explosionScale$OFFSET = $LAYOUT.byteOffset(groupElement("explosionScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float explosionScale
     * }
     */
    public static final long explosionScale$offset() {
        return explosionScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float explosionScale
     * }
     */
    public static float explosionScale(MemorySegment struct) {
        return struct.get(explosionScale$LAYOUT, explosionScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float explosionScale
     * }
     */
    public static void explosionScale(MemorySegment struct, float fieldValue) {
        struct.set(explosionScale$LAYOUT, explosionScale$OFFSET, fieldValue);
    }

    private static final GroupLayout filter$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Filter filter
     * }
     */
    public static final GroupLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Filter filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Filter filter
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.asSlice(filter$OFFSET, filter$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Filter filter
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, filter$OFFSET, filter$LAYOUT.byteSize());
    }

    private static final OfBoolean enableCustomFiltering$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableCustomFiltering"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableCustomFiltering
     * }
     */
    public static final OfBoolean enableCustomFiltering$layout() {
        return enableCustomFiltering$LAYOUT;
    }

    private static final long enableCustomFiltering$OFFSET = $LAYOUT.byteOffset(groupElement("enableCustomFiltering"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableCustomFiltering
     * }
     */
    public static final long enableCustomFiltering$offset() {
        return enableCustomFiltering$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableCustomFiltering
     * }
     */
    public static boolean enableCustomFiltering(MemorySegment struct) {
        return struct.get(enableCustomFiltering$LAYOUT, enableCustomFiltering$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableCustomFiltering
     * }
     */
    public static void enableCustomFiltering(MemorySegment struct, boolean fieldValue) {
        struct.set(enableCustomFiltering$LAYOUT, enableCustomFiltering$OFFSET, fieldValue);
    }

    private static final OfBoolean isSensor$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("isSensor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool isSensor
     * }
     */
    public static final OfBoolean isSensor$layout() {
        return isSensor$LAYOUT;
    }

    private static final long isSensor$OFFSET = $LAYOUT.byteOffset(groupElement("isSensor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool isSensor
     * }
     */
    public static final long isSensor$offset() {
        return isSensor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool isSensor
     * }
     */
    public static boolean isSensor(MemorySegment struct) {
        return struct.get(isSensor$LAYOUT, isSensor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool isSensor
     * }
     */
    public static void isSensor(MemorySegment struct, boolean fieldValue) {
        struct.set(isSensor$LAYOUT, isSensor$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSensorEvents$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSensorEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSensorEvents
     * }
     */
    public static final OfBoolean enableSensorEvents$layout() {
        return enableSensorEvents$LAYOUT;
    }

    private static final long enableSensorEvents$OFFSET = $LAYOUT.byteOffset(groupElement("enableSensorEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSensorEvents
     * }
     */
    public static final long enableSensorEvents$offset() {
        return enableSensorEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSensorEvents
     * }
     */
    public static boolean enableSensorEvents(MemorySegment struct) {
        return struct.get(enableSensorEvents$LAYOUT, enableSensorEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSensorEvents
     * }
     */
    public static void enableSensorEvents(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSensorEvents$LAYOUT, enableSensorEvents$OFFSET, fieldValue);
    }

    private static final OfBoolean enableContactEvents$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableContactEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableContactEvents
     * }
     */
    public static final OfBoolean enableContactEvents$layout() {
        return enableContactEvents$LAYOUT;
    }

    private static final long enableContactEvents$OFFSET = $LAYOUT.byteOffset(groupElement("enableContactEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableContactEvents
     * }
     */
    public static final long enableContactEvents$offset() {
        return enableContactEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableContactEvents
     * }
     */
    public static boolean enableContactEvents(MemorySegment struct) {
        return struct.get(enableContactEvents$LAYOUT, enableContactEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableContactEvents
     * }
     */
    public static void enableContactEvents(MemorySegment struct, boolean fieldValue) {
        struct.set(enableContactEvents$LAYOUT, enableContactEvents$OFFSET, fieldValue);
    }

    private static final OfBoolean enableHitEvents$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableHitEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableHitEvents
     * }
     */
    public static final OfBoolean enableHitEvents$layout() {
        return enableHitEvents$LAYOUT;
    }

    private static final long enableHitEvents$OFFSET = $LAYOUT.byteOffset(groupElement("enableHitEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableHitEvents
     * }
     */
    public static final long enableHitEvents$offset() {
        return enableHitEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableHitEvents
     * }
     */
    public static boolean enableHitEvents(MemorySegment struct) {
        return struct.get(enableHitEvents$LAYOUT, enableHitEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableHitEvents
     * }
     */
    public static void enableHitEvents(MemorySegment struct, boolean fieldValue) {
        struct.set(enableHitEvents$LAYOUT, enableHitEvents$OFFSET, fieldValue);
    }

    private static final OfBoolean enablePreSolveEvents$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enablePreSolveEvents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enablePreSolveEvents
     * }
     */
    public static final OfBoolean enablePreSolveEvents$layout() {
        return enablePreSolveEvents$LAYOUT;
    }

    private static final long enablePreSolveEvents$OFFSET = $LAYOUT.byteOffset(groupElement("enablePreSolveEvents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enablePreSolveEvents
     * }
     */
    public static final long enablePreSolveEvents$offset() {
        return enablePreSolveEvents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enablePreSolveEvents
     * }
     */
    public static boolean enablePreSolveEvents(MemorySegment struct) {
        return struct.get(enablePreSolveEvents$LAYOUT, enablePreSolveEvents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enablePreSolveEvents
     * }
     */
    public static void enablePreSolveEvents(MemorySegment struct, boolean fieldValue) {
        struct.set(enablePreSolveEvents$LAYOUT, enablePreSolveEvents$OFFSET, fieldValue);
    }

    private static final OfBoolean invokeContactCreation$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("invokeContactCreation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool invokeContactCreation
     * }
     */
    public static final OfBoolean invokeContactCreation$layout() {
        return invokeContactCreation$LAYOUT;
    }

    private static final long invokeContactCreation$OFFSET = $LAYOUT.byteOffset(groupElement("invokeContactCreation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool invokeContactCreation
     * }
     */
    public static final long invokeContactCreation$offset() {
        return invokeContactCreation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool invokeContactCreation
     * }
     */
    public static boolean invokeContactCreation(MemorySegment struct) {
        return struct.get(invokeContactCreation$LAYOUT, invokeContactCreation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool invokeContactCreation
     * }
     */
    public static void invokeContactCreation(MemorySegment struct, boolean fieldValue) {
        struct.set(invokeContactCreation$LAYOUT, invokeContactCreation$OFFSET, fieldValue);
    }

    private static final OfBoolean updateBodyMass$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("updateBodyMass"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool updateBodyMass
     * }
     */
    public static final OfBoolean updateBodyMass$layout() {
        return updateBodyMass$LAYOUT;
    }

    private static final long updateBodyMass$OFFSET = $LAYOUT.byteOffset(groupElement("updateBodyMass"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool updateBodyMass
     * }
     */
    public static final long updateBodyMass$offset() {
        return updateBodyMass$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool updateBodyMass
     * }
     */
    public static boolean updateBodyMass(MemorySegment struct) {
        return struct.get(updateBodyMass$LAYOUT, updateBodyMass$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool updateBodyMass
     * }
     */
    public static void updateBodyMass(MemorySegment struct, boolean fieldValue) {
        struct.set(updateBodyMass$LAYOUT, updateBodyMass$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSpeculativeContact$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSpeculativeContact"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSpeculativeContact
     * }
     */
    public static final OfBoolean enableSpeculativeContact$layout() {
        return enableSpeculativeContact$LAYOUT;
    }

    private static final long enableSpeculativeContact$OFFSET = $LAYOUT.byteOffset(groupElement("enableSpeculativeContact"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSpeculativeContact
     * }
     */
    public static final long enableSpeculativeContact$offset() {
        return enableSpeculativeContact$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSpeculativeContact
     * }
     */
    public static boolean enableSpeculativeContact(MemorySegment struct) {
        return struct.get(enableSpeculativeContact$LAYOUT, enableSpeculativeContact$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSpeculativeContact
     * }
     */
    public static void enableSpeculativeContact(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSpeculativeContact$LAYOUT, enableSpeculativeContact$OFFSET, fieldValue);
    }

    private static final OfInt internalValue$LAYOUT = (OfInt)$LAYOUT.select(groupElement("internalValue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static final OfInt internalValue$layout() {
        return internalValue$LAYOUT;
    }

    private static final long internalValue$OFFSET = $LAYOUT.byteOffset(groupElement("internalValue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static final long internalValue$offset() {
        return internalValue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static int internalValue(MemorySegment struct) {
        return struct.get(internalValue$LAYOUT, internalValue$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static void internalValue(MemorySegment struct, int fieldValue) {
        struct.set(internalValue$LAYOUT, internalValue$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

