// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3SphericalJointDef {
 *     b3JointDef base;
 *     _Bool enableSpring;
 *     float hertz;
 *     float dampingRatio;
 *     b3Quat targetRotation;
 *     _Bool enableConeLimit;
 *     float coneAngle;
 *     _Bool enableTwistLimit;
 *     float lowerTwistAngle;
 *     float upperTwistAngle;
 *     _Bool enableMotor;
 *     float maxMotorTorque;
 *     b3Vec3 motorVelocity;
 * }
 * }
 */
public class b3SphericalJointDef {

    b3SphericalJointDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3JointDef.layout().withName("base"),
        Box3D.C_BOOL.withName("enableSpring"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("hertz"),
        Box3D.C_FLOAT.withName("dampingRatio"),
        b3Quat.layout().withName("targetRotation"),
        Box3D.C_BOOL.withName("enableConeLimit"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("coneAngle"),
        Box3D.C_BOOL.withName("enableTwistLimit"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("lowerTwistAngle"),
        Box3D.C_FLOAT.withName("upperTwistAngle"),
        Box3D.C_BOOL.withName("enableMotor"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("maxMotorTorque"),
        b3Vec3.layout().withName("motorVelocity"),
        MemoryLayout.paddingLayout(4)
    ).withName("b3SphericalJointDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    private static final OfBoolean enableSpring$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSpring"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static final OfBoolean enableSpring$layout() {
        return enableSpring$LAYOUT;
    }

    private static final long enableSpring$OFFSET = $LAYOUT.byteOffset(groupElement("enableSpring"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static final long enableSpring$offset() {
        return enableSpring$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static boolean enableSpring(MemorySegment struct) {
        return struct.get(enableSpring$LAYOUT, enableSpring$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSpring
     * }
     */
    public static void enableSpring(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSpring$LAYOUT, enableSpring$OFFSET, fieldValue);
    }

    private static final OfFloat hertz$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("hertz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static final OfFloat hertz$layout() {
        return hertz$LAYOUT;
    }

    private static final long hertz$OFFSET = $LAYOUT.byteOffset(groupElement("hertz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static final long hertz$offset() {
        return hertz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static float hertz(MemorySegment struct) {
        return struct.get(hertz$LAYOUT, hertz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hertz
     * }
     */
    public static void hertz(MemorySegment struct, float fieldValue) {
        struct.set(hertz$LAYOUT, hertz$OFFSET, fieldValue);
    }

    private static final OfFloat dampingRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("dampingRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static final OfFloat dampingRatio$layout() {
        return dampingRatio$LAYOUT;
    }

    private static final long dampingRatio$OFFSET = $LAYOUT.byteOffset(groupElement("dampingRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static final long dampingRatio$offset() {
        return dampingRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static float dampingRatio(MemorySegment struct) {
        return struct.get(dampingRatio$LAYOUT, dampingRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float dampingRatio
     * }
     */
    public static void dampingRatio(MemorySegment struct, float fieldValue) {
        struct.set(dampingRatio$LAYOUT, dampingRatio$OFFSET, fieldValue);
    }

    private static final GroupLayout targetRotation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("targetRotation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Quat targetRotation
     * }
     */
    public static final GroupLayout targetRotation$layout() {
        return targetRotation$LAYOUT;
    }

    private static final long targetRotation$OFFSET = $LAYOUT.byteOffset(groupElement("targetRotation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Quat targetRotation
     * }
     */
    public static final long targetRotation$offset() {
        return targetRotation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Quat targetRotation
     * }
     */
    public static MemorySegment targetRotation(MemorySegment struct) {
        return struct.asSlice(targetRotation$OFFSET, targetRotation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Quat targetRotation
     * }
     */
    public static void targetRotation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, targetRotation$OFFSET, targetRotation$LAYOUT.byteSize());
    }

    private static final OfBoolean enableConeLimit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableConeLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableConeLimit
     * }
     */
    public static final OfBoolean enableConeLimit$layout() {
        return enableConeLimit$LAYOUT;
    }

    private static final long enableConeLimit$OFFSET = $LAYOUT.byteOffset(groupElement("enableConeLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableConeLimit
     * }
     */
    public static final long enableConeLimit$offset() {
        return enableConeLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableConeLimit
     * }
     */
    public static boolean enableConeLimit(MemorySegment struct) {
        return struct.get(enableConeLimit$LAYOUT, enableConeLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableConeLimit
     * }
     */
    public static void enableConeLimit(MemorySegment struct, boolean fieldValue) {
        struct.set(enableConeLimit$LAYOUT, enableConeLimit$OFFSET, fieldValue);
    }

    private static final OfFloat coneAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("coneAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float coneAngle
     * }
     */
    public static final OfFloat coneAngle$layout() {
        return coneAngle$LAYOUT;
    }

    private static final long coneAngle$OFFSET = $LAYOUT.byteOffset(groupElement("coneAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float coneAngle
     * }
     */
    public static final long coneAngle$offset() {
        return coneAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float coneAngle
     * }
     */
    public static float coneAngle(MemorySegment struct) {
        return struct.get(coneAngle$LAYOUT, coneAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float coneAngle
     * }
     */
    public static void coneAngle(MemorySegment struct, float fieldValue) {
        struct.set(coneAngle$LAYOUT, coneAngle$OFFSET, fieldValue);
    }

    private static final OfBoolean enableTwistLimit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableTwistLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableTwistLimit
     * }
     */
    public static final OfBoolean enableTwistLimit$layout() {
        return enableTwistLimit$LAYOUT;
    }

    private static final long enableTwistLimit$OFFSET = $LAYOUT.byteOffset(groupElement("enableTwistLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableTwistLimit
     * }
     */
    public static final long enableTwistLimit$offset() {
        return enableTwistLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableTwistLimit
     * }
     */
    public static boolean enableTwistLimit(MemorySegment struct) {
        return struct.get(enableTwistLimit$LAYOUT, enableTwistLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableTwistLimit
     * }
     */
    public static void enableTwistLimit(MemorySegment struct, boolean fieldValue) {
        struct.set(enableTwistLimit$LAYOUT, enableTwistLimit$OFFSET, fieldValue);
    }

    private static final OfFloat lowerTwistAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("lowerTwistAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float lowerTwistAngle
     * }
     */
    public static final OfFloat lowerTwistAngle$layout() {
        return lowerTwistAngle$LAYOUT;
    }

    private static final long lowerTwistAngle$OFFSET = $LAYOUT.byteOffset(groupElement("lowerTwistAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float lowerTwistAngle
     * }
     */
    public static final long lowerTwistAngle$offset() {
        return lowerTwistAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float lowerTwistAngle
     * }
     */
    public static float lowerTwistAngle(MemorySegment struct) {
        return struct.get(lowerTwistAngle$LAYOUT, lowerTwistAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float lowerTwistAngle
     * }
     */
    public static void lowerTwistAngle(MemorySegment struct, float fieldValue) {
        struct.set(lowerTwistAngle$LAYOUT, lowerTwistAngle$OFFSET, fieldValue);
    }

    private static final OfFloat upperTwistAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("upperTwistAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float upperTwistAngle
     * }
     */
    public static final OfFloat upperTwistAngle$layout() {
        return upperTwistAngle$LAYOUT;
    }

    private static final long upperTwistAngle$OFFSET = $LAYOUT.byteOffset(groupElement("upperTwistAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float upperTwistAngle
     * }
     */
    public static final long upperTwistAngle$offset() {
        return upperTwistAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float upperTwistAngle
     * }
     */
    public static float upperTwistAngle(MemorySegment struct) {
        return struct.get(upperTwistAngle$LAYOUT, upperTwistAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float upperTwistAngle
     * }
     */
    public static void upperTwistAngle(MemorySegment struct, float fieldValue) {
        struct.set(upperTwistAngle$LAYOUT, upperTwistAngle$OFFSET, fieldValue);
    }

    private static final OfBoolean enableMotor$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableMotor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static final OfBoolean enableMotor$layout() {
        return enableMotor$LAYOUT;
    }

    private static final long enableMotor$OFFSET = $LAYOUT.byteOffset(groupElement("enableMotor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static final long enableMotor$offset() {
        return enableMotor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static boolean enableMotor(MemorySegment struct) {
        return struct.get(enableMotor$LAYOUT, enableMotor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableMotor
     * }
     */
    public static void enableMotor(MemorySegment struct, boolean fieldValue) {
        struct.set(enableMotor$LAYOUT, enableMotor$OFFSET, fieldValue);
    }

    private static final OfFloat maxMotorTorque$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxMotorTorque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static final OfFloat maxMotorTorque$layout() {
        return maxMotorTorque$LAYOUT;
    }

    private static final long maxMotorTorque$OFFSET = $LAYOUT.byteOffset(groupElement("maxMotorTorque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static final long maxMotorTorque$offset() {
        return maxMotorTorque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static float maxMotorTorque(MemorySegment struct) {
        return struct.get(maxMotorTorque$LAYOUT, maxMotorTorque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxMotorTorque
     * }
     */
    public static void maxMotorTorque(MemorySegment struct, float fieldValue) {
        struct.set(maxMotorTorque$LAYOUT, maxMotorTorque$OFFSET, fieldValue);
    }

    private static final GroupLayout motorVelocity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("motorVelocity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 motorVelocity
     * }
     */
    public static final GroupLayout motorVelocity$layout() {
        return motorVelocity$LAYOUT;
    }

    private static final long motorVelocity$OFFSET = $LAYOUT.byteOffset(groupElement("motorVelocity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 motorVelocity
     * }
     */
    public static final long motorVelocity$offset() {
        return motorVelocity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 motorVelocity
     * }
     */
    public static MemorySegment motorVelocity(MemorySegment struct) {
        return struct.asSlice(motorVelocity$OFFSET, motorVelocity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 motorVelocity
     * }
     */
    public static void motorVelocity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, motorVelocity$OFFSET, motorVelocity$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

