// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3Sweep {
 *     b3Vec3 localCenter;
 *     b3Vec3 c1;
 *     b3Vec3 c2;
 *     b3Quat q1;
 *     b3Quat q2;
 * }
 * }
 */
public class b3Sweep {

    b3Sweep() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Vec3.layout().withName("localCenter"),
        b3Vec3.layout().withName("c1"),
        b3Vec3.layout().withName("c2"),
        b3Quat.layout().withName("q1"),
        b3Quat.layout().withName("q2")
    ).withName("b3Sweep");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout localCenter$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("localCenter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 localCenter
     * }
     */
    public static final GroupLayout localCenter$layout() {
        return localCenter$LAYOUT;
    }

    private static final long localCenter$OFFSET = $LAYOUT.byteOffset(groupElement("localCenter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 localCenter
     * }
     */
    public static final long localCenter$offset() {
        return localCenter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 localCenter
     * }
     */
    public static MemorySegment localCenter(MemorySegment struct) {
        return struct.asSlice(localCenter$OFFSET, localCenter$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 localCenter
     * }
     */
    public static void localCenter(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, localCenter$OFFSET, localCenter$LAYOUT.byteSize());
    }

    private static final GroupLayout c1$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("c1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 c1
     * }
     */
    public static final GroupLayout c1$layout() {
        return c1$LAYOUT;
    }

    private static final long c1$OFFSET = $LAYOUT.byteOffset(groupElement("c1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 c1
     * }
     */
    public static final long c1$offset() {
        return c1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 c1
     * }
     */
    public static MemorySegment c1(MemorySegment struct) {
        return struct.asSlice(c1$OFFSET, c1$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 c1
     * }
     */
    public static void c1(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, c1$OFFSET, c1$LAYOUT.byteSize());
    }

    private static final GroupLayout c2$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("c2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 c2
     * }
     */
    public static final GroupLayout c2$layout() {
        return c2$LAYOUT;
    }

    private static final long c2$OFFSET = $LAYOUT.byteOffset(groupElement("c2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 c2
     * }
     */
    public static final long c2$offset() {
        return c2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 c2
     * }
     */
    public static MemorySegment c2(MemorySegment struct) {
        return struct.asSlice(c2$OFFSET, c2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 c2
     * }
     */
    public static void c2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, c2$OFFSET, c2$LAYOUT.byteSize());
    }

    private static final GroupLayout q1$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("q1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Quat q1
     * }
     */
    public static final GroupLayout q1$layout() {
        return q1$LAYOUT;
    }

    private static final long q1$OFFSET = $LAYOUT.byteOffset(groupElement("q1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Quat q1
     * }
     */
    public static final long q1$offset() {
        return q1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Quat q1
     * }
     */
    public static MemorySegment q1(MemorySegment struct) {
        return struct.asSlice(q1$OFFSET, q1$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Quat q1
     * }
     */
    public static void q1(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, q1$OFFSET, q1$LAYOUT.byteSize());
    }

    private static final GroupLayout q2$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("q2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Quat q2
     * }
     */
    public static final GroupLayout q2$layout() {
        return q2$LAYOUT;
    }

    private static final long q2$OFFSET = $LAYOUT.byteOffset(groupElement("q2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Quat q2
     * }
     */
    public static final long q2$offset() {
        return q2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Quat q2
     * }
     */
    public static MemorySegment q2(MemorySegment struct) {
        return struct.asSlice(q2$OFFSET, q2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Quat q2
     * }
     */
    public static void q2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, q2$OFFSET, q2$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

