// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3TreeNode {
 *     b3AABB aabb;
 *     uint64_t categoryBits;
 *     union {
 *         b3TreeNodeChildren children;
 *         uint64_t userData;
 *     };
 *     union {
 *         int parent;
 *         int next;
 *     };
 *     uint16_t height;
 *     uint16_t flags;
 * }
 * }
 */
public class b3TreeNode {

    b3TreeNode() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3AABB.layout().withName("aabb"),
        Box3D.C_LONG_LONG.withName("categoryBits"),
        MemoryLayout.unionLayout(
            b3TreeNodeChildren.layout().withName("children"),
            Box3D.C_LONG_LONG.withName("userData")
        ).withName("$anon$1704:2"),
        MemoryLayout.unionLayout(
            Box3D.C_INT.withName("parent"),
            Box3D.C_INT.withName("next")
        ).withName("$anon$1713:2"),
        Box3D.C_SHORT.withName("height"),
        Box3D.C_SHORT.withName("flags")
    ).withName("b3TreeNode");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout aabb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("aabb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final GroupLayout aabb$layout() {
        return aabb$LAYOUT;
    }

    private static final long aabb$OFFSET = $LAYOUT.byteOffset(groupElement("aabb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static final long aabb$offset() {
        return aabb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static MemorySegment aabb(MemorySegment struct) {
        return struct.asSlice(aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3AABB aabb
     * }
     */
    public static void aabb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, aabb$OFFSET, aabb$LAYOUT.byteSize());
    }

    private static final OfLong categoryBits$LAYOUT = (OfLong)$LAYOUT.select(groupElement("categoryBits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t categoryBits
     * }
     */
    public static final OfLong categoryBits$layout() {
        return categoryBits$LAYOUT;
    }

    private static final long categoryBits$OFFSET = $LAYOUT.byteOffset(groupElement("categoryBits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t categoryBits
     * }
     */
    public static final long categoryBits$offset() {
        return categoryBits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t categoryBits
     * }
     */
    public static long categoryBits(MemorySegment struct) {
        return struct.get(categoryBits$LAYOUT, categoryBits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t categoryBits
     * }
     */
    public static void categoryBits(MemorySegment struct, long fieldValue) {
        struct.set(categoryBits$LAYOUT, categoryBits$OFFSET, fieldValue);
    }

    private static final GroupLayout children$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$1704:2"), groupElement("children"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3TreeNodeChildren children
     * }
     */
    public static final GroupLayout children$layout() {
        return children$LAYOUT;
    }

    private static final long children$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$1704:2"), groupElement("children"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3TreeNodeChildren children
     * }
     */
    public static final long children$offset() {
        return children$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3TreeNodeChildren children
     * }
     */
    public static MemorySegment children(MemorySegment struct) {
        return struct.asSlice(children$OFFSET, children$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3TreeNodeChildren children
     * }
     */
    public static void children(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, children$OFFSET, children$LAYOUT.byteSize());
    }

    private static final OfLong userData$LAYOUT = (OfLong)$LAYOUT.select(groupElement("$anon$1704:2"), groupElement("userData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t userData
     * }
     */
    public static final OfLong userData$layout() {
        return userData$LAYOUT;
    }

    private static final long userData$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$1704:2"), groupElement("userData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t userData
     * }
     */
    public static final long userData$offset() {
        return userData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t userData
     * }
     */
    public static long userData(MemorySegment struct) {
        return struct.get(userData$LAYOUT, userData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t userData
     * }
     */
    public static void userData(MemorySegment struct, long fieldValue) {
        struct.set(userData$LAYOUT, userData$OFFSET, fieldValue);
    }

    private static final OfInt parent$LAYOUT = (OfInt)$LAYOUT.select(groupElement("$anon$1713:2"), groupElement("parent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int parent
     * }
     */
    public static final OfInt parent$layout() {
        return parent$LAYOUT;
    }

    private static final long parent$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$1713:2"), groupElement("parent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int parent
     * }
     */
    public static final long parent$offset() {
        return parent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int parent
     * }
     */
    public static int parent(MemorySegment struct) {
        return struct.get(parent$LAYOUT, parent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int parent
     * }
     */
    public static void parent(MemorySegment struct, int fieldValue) {
        struct.set(parent$LAYOUT, parent$OFFSET, fieldValue);
    }

    private static final OfInt next$LAYOUT = (OfInt)$LAYOUT.select(groupElement("$anon$1713:2"), groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int next
     * }
     */
    public static final OfInt next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$1713:2"), groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int next
     * }
     */
    public static int next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int next
     * }
     */
    public static void next(MemorySegment struct, int fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    private static final OfShort height$LAYOUT = (OfShort)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t height
     * }
     */
    public static final OfShort height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t height
     * }
     */
    public static short height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t height
     * }
     */
    public static void height(MemorySegment struct, short fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfShort flags$LAYOUT = (OfShort)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t flags
     * }
     */
    public static final OfShort flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t flags
     * }
     */
    public static short flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t flags
     * }
     */
    public static void flags(MemorySegment struct, short fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

