// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3TreeNodeChildren {
 *     int child1;
 *     int child2;
 * }
 * }
 */
public class b3TreeNodeChildren {

    b3TreeNodeChildren() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box3D.C_INT.withName("child1"),
        Box3D.C_INT.withName("child2")
    ).withName("b3TreeNodeChildren");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt child1$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int child1
     * }
     */
    public static final OfInt child1$layout() {
        return child1$LAYOUT;
    }

    private static final long child1$OFFSET = $LAYOUT.byteOffset(groupElement("child1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int child1
     * }
     */
    public static final long child1$offset() {
        return child1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int child1
     * }
     */
    public static int child1(MemorySegment struct) {
        return struct.get(child1$LAYOUT, child1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int child1
     * }
     */
    public static void child1(MemorySegment struct, int fieldValue) {
        struct.set(child1$LAYOUT, child1$OFFSET, fieldValue);
    }

    private static final OfInt child2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int child2
     * }
     */
    public static final OfInt child2$layout() {
        return child2$LAYOUT;
    }

    private static final long child2$OFFSET = $LAYOUT.byteOffset(groupElement("child2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int child2
     * }
     */
    public static final long child2$offset() {
        return child2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int child2
     * }
     */
    public static int child2(MemorySegment struct) {
        return struct.get(child2$LAYOUT, child2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int child2
     * }
     */
    public static void child2(MemorySegment struct, int fieldValue) {
        struct.set(child2$LAYOUT, child2$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

