// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3WheelJointDef {
 *     b3JointDef base;
 *     _Bool enableSuspensionSpring;
 *     float suspensionHertz;
 *     float suspensionDampingRatio;
 *     _Bool enableSuspensionLimit;
 *     float lowerSuspensionLimit;
 *     float upperSuspensionLimit;
 *     _Bool enableSpinMotor;
 *     float maxSpinTorque;
 *     float spinSpeed;
 *     _Bool enableSteering;
 *     float steeringHertz;
 *     float steeringDampingRatio;
 *     float targetSteeringAngle;
 *     float maxSteeringTorque;
 *     _Bool enableSteeringLimit;
 *     float lowerSteeringLimit;
 *     float upperSteeringLimit;
 * }
 * }
 */
public class b3WheelJointDef {

    b3WheelJointDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3JointDef.layout().withName("base"),
        Box3D.C_BOOL.withName("enableSuspensionSpring"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("suspensionHertz"),
        Box3D.C_FLOAT.withName("suspensionDampingRatio"),
        Box3D.C_BOOL.withName("enableSuspensionLimit"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("lowerSuspensionLimit"),
        Box3D.C_FLOAT.withName("upperSuspensionLimit"),
        Box3D.C_BOOL.withName("enableSpinMotor"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("maxSpinTorque"),
        Box3D.C_FLOAT.withName("spinSpeed"),
        Box3D.C_BOOL.withName("enableSteering"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("steeringHertz"),
        Box3D.C_FLOAT.withName("steeringDampingRatio"),
        Box3D.C_FLOAT.withName("targetSteeringAngle"),
        Box3D.C_FLOAT.withName("maxSteeringTorque"),
        Box3D.C_BOOL.withName("enableSteeringLimit"),
        MemoryLayout.paddingLayout(3),
        Box3D.C_FLOAT.withName("lowerSteeringLimit"),
        Box3D.C_FLOAT.withName("upperSteeringLimit"),
        MemoryLayout.paddingLayout(4)
    ).withName("b3WheelJointDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3JointDef base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    private static final OfBoolean enableSuspensionSpring$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSuspensionSpring"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionSpring
     * }
     */
    public static final OfBoolean enableSuspensionSpring$layout() {
        return enableSuspensionSpring$LAYOUT;
    }

    private static final long enableSuspensionSpring$OFFSET = $LAYOUT.byteOffset(groupElement("enableSuspensionSpring"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionSpring
     * }
     */
    public static final long enableSuspensionSpring$offset() {
        return enableSuspensionSpring$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionSpring
     * }
     */
    public static boolean enableSuspensionSpring(MemorySegment struct) {
        return struct.get(enableSuspensionSpring$LAYOUT, enableSuspensionSpring$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionSpring
     * }
     */
    public static void enableSuspensionSpring(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSuspensionSpring$LAYOUT, enableSuspensionSpring$OFFSET, fieldValue);
    }

    private static final OfFloat suspensionHertz$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("suspensionHertz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float suspensionHertz
     * }
     */
    public static final OfFloat suspensionHertz$layout() {
        return suspensionHertz$LAYOUT;
    }

    private static final long suspensionHertz$OFFSET = $LAYOUT.byteOffset(groupElement("suspensionHertz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float suspensionHertz
     * }
     */
    public static final long suspensionHertz$offset() {
        return suspensionHertz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float suspensionHertz
     * }
     */
    public static float suspensionHertz(MemorySegment struct) {
        return struct.get(suspensionHertz$LAYOUT, suspensionHertz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float suspensionHertz
     * }
     */
    public static void suspensionHertz(MemorySegment struct, float fieldValue) {
        struct.set(suspensionHertz$LAYOUT, suspensionHertz$OFFSET, fieldValue);
    }

    private static final OfFloat suspensionDampingRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("suspensionDampingRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float suspensionDampingRatio
     * }
     */
    public static final OfFloat suspensionDampingRatio$layout() {
        return suspensionDampingRatio$LAYOUT;
    }

    private static final long suspensionDampingRatio$OFFSET = $LAYOUT.byteOffset(groupElement("suspensionDampingRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float suspensionDampingRatio
     * }
     */
    public static final long suspensionDampingRatio$offset() {
        return suspensionDampingRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float suspensionDampingRatio
     * }
     */
    public static float suspensionDampingRatio(MemorySegment struct) {
        return struct.get(suspensionDampingRatio$LAYOUT, suspensionDampingRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float suspensionDampingRatio
     * }
     */
    public static void suspensionDampingRatio(MemorySegment struct, float fieldValue) {
        struct.set(suspensionDampingRatio$LAYOUT, suspensionDampingRatio$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSuspensionLimit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSuspensionLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionLimit
     * }
     */
    public static final OfBoolean enableSuspensionLimit$layout() {
        return enableSuspensionLimit$LAYOUT;
    }

    private static final long enableSuspensionLimit$OFFSET = $LAYOUT.byteOffset(groupElement("enableSuspensionLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionLimit
     * }
     */
    public static final long enableSuspensionLimit$offset() {
        return enableSuspensionLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionLimit
     * }
     */
    public static boolean enableSuspensionLimit(MemorySegment struct) {
        return struct.get(enableSuspensionLimit$LAYOUT, enableSuspensionLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSuspensionLimit
     * }
     */
    public static void enableSuspensionLimit(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSuspensionLimit$LAYOUT, enableSuspensionLimit$OFFSET, fieldValue);
    }

    private static final OfFloat lowerSuspensionLimit$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("lowerSuspensionLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float lowerSuspensionLimit
     * }
     */
    public static final OfFloat lowerSuspensionLimit$layout() {
        return lowerSuspensionLimit$LAYOUT;
    }

    private static final long lowerSuspensionLimit$OFFSET = $LAYOUT.byteOffset(groupElement("lowerSuspensionLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float lowerSuspensionLimit
     * }
     */
    public static final long lowerSuspensionLimit$offset() {
        return lowerSuspensionLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float lowerSuspensionLimit
     * }
     */
    public static float lowerSuspensionLimit(MemorySegment struct) {
        return struct.get(lowerSuspensionLimit$LAYOUT, lowerSuspensionLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float lowerSuspensionLimit
     * }
     */
    public static void lowerSuspensionLimit(MemorySegment struct, float fieldValue) {
        struct.set(lowerSuspensionLimit$LAYOUT, lowerSuspensionLimit$OFFSET, fieldValue);
    }

    private static final OfFloat upperSuspensionLimit$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("upperSuspensionLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float upperSuspensionLimit
     * }
     */
    public static final OfFloat upperSuspensionLimit$layout() {
        return upperSuspensionLimit$LAYOUT;
    }

    private static final long upperSuspensionLimit$OFFSET = $LAYOUT.byteOffset(groupElement("upperSuspensionLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float upperSuspensionLimit
     * }
     */
    public static final long upperSuspensionLimit$offset() {
        return upperSuspensionLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float upperSuspensionLimit
     * }
     */
    public static float upperSuspensionLimit(MemorySegment struct) {
        return struct.get(upperSuspensionLimit$LAYOUT, upperSuspensionLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float upperSuspensionLimit
     * }
     */
    public static void upperSuspensionLimit(MemorySegment struct, float fieldValue) {
        struct.set(upperSuspensionLimit$LAYOUT, upperSuspensionLimit$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSpinMotor$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSpinMotor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSpinMotor
     * }
     */
    public static final OfBoolean enableSpinMotor$layout() {
        return enableSpinMotor$LAYOUT;
    }

    private static final long enableSpinMotor$OFFSET = $LAYOUT.byteOffset(groupElement("enableSpinMotor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSpinMotor
     * }
     */
    public static final long enableSpinMotor$offset() {
        return enableSpinMotor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSpinMotor
     * }
     */
    public static boolean enableSpinMotor(MemorySegment struct) {
        return struct.get(enableSpinMotor$LAYOUT, enableSpinMotor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSpinMotor
     * }
     */
    public static void enableSpinMotor(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSpinMotor$LAYOUT, enableSpinMotor$OFFSET, fieldValue);
    }

    private static final OfFloat maxSpinTorque$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxSpinTorque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxSpinTorque
     * }
     */
    public static final OfFloat maxSpinTorque$layout() {
        return maxSpinTorque$LAYOUT;
    }

    private static final long maxSpinTorque$OFFSET = $LAYOUT.byteOffset(groupElement("maxSpinTorque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxSpinTorque
     * }
     */
    public static final long maxSpinTorque$offset() {
        return maxSpinTorque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxSpinTorque
     * }
     */
    public static float maxSpinTorque(MemorySegment struct) {
        return struct.get(maxSpinTorque$LAYOUT, maxSpinTorque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxSpinTorque
     * }
     */
    public static void maxSpinTorque(MemorySegment struct, float fieldValue) {
        struct.set(maxSpinTorque$LAYOUT, maxSpinTorque$OFFSET, fieldValue);
    }

    private static final OfFloat spinSpeed$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("spinSpeed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float spinSpeed
     * }
     */
    public static final OfFloat spinSpeed$layout() {
        return spinSpeed$LAYOUT;
    }

    private static final long spinSpeed$OFFSET = $LAYOUT.byteOffset(groupElement("spinSpeed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float spinSpeed
     * }
     */
    public static final long spinSpeed$offset() {
        return spinSpeed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float spinSpeed
     * }
     */
    public static float spinSpeed(MemorySegment struct) {
        return struct.get(spinSpeed$LAYOUT, spinSpeed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float spinSpeed
     * }
     */
    public static void spinSpeed(MemorySegment struct, float fieldValue) {
        struct.set(spinSpeed$LAYOUT, spinSpeed$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSteering$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSteering"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSteering
     * }
     */
    public static final OfBoolean enableSteering$layout() {
        return enableSteering$LAYOUT;
    }

    private static final long enableSteering$OFFSET = $LAYOUT.byteOffset(groupElement("enableSteering"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSteering
     * }
     */
    public static final long enableSteering$offset() {
        return enableSteering$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSteering
     * }
     */
    public static boolean enableSteering(MemorySegment struct) {
        return struct.get(enableSteering$LAYOUT, enableSteering$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSteering
     * }
     */
    public static void enableSteering(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSteering$LAYOUT, enableSteering$OFFSET, fieldValue);
    }

    private static final OfFloat steeringHertz$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("steeringHertz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float steeringHertz
     * }
     */
    public static final OfFloat steeringHertz$layout() {
        return steeringHertz$LAYOUT;
    }

    private static final long steeringHertz$OFFSET = $LAYOUT.byteOffset(groupElement("steeringHertz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float steeringHertz
     * }
     */
    public static final long steeringHertz$offset() {
        return steeringHertz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float steeringHertz
     * }
     */
    public static float steeringHertz(MemorySegment struct) {
        return struct.get(steeringHertz$LAYOUT, steeringHertz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float steeringHertz
     * }
     */
    public static void steeringHertz(MemorySegment struct, float fieldValue) {
        struct.set(steeringHertz$LAYOUT, steeringHertz$OFFSET, fieldValue);
    }

    private static final OfFloat steeringDampingRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("steeringDampingRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float steeringDampingRatio
     * }
     */
    public static final OfFloat steeringDampingRatio$layout() {
        return steeringDampingRatio$LAYOUT;
    }

    private static final long steeringDampingRatio$OFFSET = $LAYOUT.byteOffset(groupElement("steeringDampingRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float steeringDampingRatio
     * }
     */
    public static final long steeringDampingRatio$offset() {
        return steeringDampingRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float steeringDampingRatio
     * }
     */
    public static float steeringDampingRatio(MemorySegment struct) {
        return struct.get(steeringDampingRatio$LAYOUT, steeringDampingRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float steeringDampingRatio
     * }
     */
    public static void steeringDampingRatio(MemorySegment struct, float fieldValue) {
        struct.set(steeringDampingRatio$LAYOUT, steeringDampingRatio$OFFSET, fieldValue);
    }

    private static final OfFloat targetSteeringAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("targetSteeringAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float targetSteeringAngle
     * }
     */
    public static final OfFloat targetSteeringAngle$layout() {
        return targetSteeringAngle$LAYOUT;
    }

    private static final long targetSteeringAngle$OFFSET = $LAYOUT.byteOffset(groupElement("targetSteeringAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float targetSteeringAngle
     * }
     */
    public static final long targetSteeringAngle$offset() {
        return targetSteeringAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float targetSteeringAngle
     * }
     */
    public static float targetSteeringAngle(MemorySegment struct) {
        return struct.get(targetSteeringAngle$LAYOUT, targetSteeringAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float targetSteeringAngle
     * }
     */
    public static void targetSteeringAngle(MemorySegment struct, float fieldValue) {
        struct.set(targetSteeringAngle$LAYOUT, targetSteeringAngle$OFFSET, fieldValue);
    }

    private static final OfFloat maxSteeringTorque$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxSteeringTorque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxSteeringTorque
     * }
     */
    public static final OfFloat maxSteeringTorque$layout() {
        return maxSteeringTorque$LAYOUT;
    }

    private static final long maxSteeringTorque$OFFSET = $LAYOUT.byteOffset(groupElement("maxSteeringTorque"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxSteeringTorque
     * }
     */
    public static final long maxSteeringTorque$offset() {
        return maxSteeringTorque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxSteeringTorque
     * }
     */
    public static float maxSteeringTorque(MemorySegment struct) {
        return struct.get(maxSteeringTorque$LAYOUT, maxSteeringTorque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxSteeringTorque
     * }
     */
    public static void maxSteeringTorque(MemorySegment struct, float fieldValue) {
        struct.set(maxSteeringTorque$LAYOUT, maxSteeringTorque$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSteeringLimit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSteeringLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSteeringLimit
     * }
     */
    public static final OfBoolean enableSteeringLimit$layout() {
        return enableSteeringLimit$LAYOUT;
    }

    private static final long enableSteeringLimit$OFFSET = $LAYOUT.byteOffset(groupElement("enableSteeringLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSteeringLimit
     * }
     */
    public static final long enableSteeringLimit$offset() {
        return enableSteeringLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSteeringLimit
     * }
     */
    public static boolean enableSteeringLimit(MemorySegment struct) {
        return struct.get(enableSteeringLimit$LAYOUT, enableSteeringLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSteeringLimit
     * }
     */
    public static void enableSteeringLimit(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSteeringLimit$LAYOUT, enableSteeringLimit$OFFSET, fieldValue);
    }

    private static final OfFloat lowerSteeringLimit$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("lowerSteeringLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float lowerSteeringLimit
     * }
     */
    public static final OfFloat lowerSteeringLimit$layout() {
        return lowerSteeringLimit$LAYOUT;
    }

    private static final long lowerSteeringLimit$OFFSET = $LAYOUT.byteOffset(groupElement("lowerSteeringLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float lowerSteeringLimit
     * }
     */
    public static final long lowerSteeringLimit$offset() {
        return lowerSteeringLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float lowerSteeringLimit
     * }
     */
    public static float lowerSteeringLimit(MemorySegment struct) {
        return struct.get(lowerSteeringLimit$LAYOUT, lowerSteeringLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float lowerSteeringLimit
     * }
     */
    public static void lowerSteeringLimit(MemorySegment struct, float fieldValue) {
        struct.set(lowerSteeringLimit$LAYOUT, lowerSteeringLimit$OFFSET, fieldValue);
    }

    private static final OfFloat upperSteeringLimit$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("upperSteeringLimit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float upperSteeringLimit
     * }
     */
    public static final OfFloat upperSteeringLimit$layout() {
        return upperSteeringLimit$LAYOUT;
    }

    private static final long upperSteeringLimit$OFFSET = $LAYOUT.byteOffset(groupElement("upperSteeringLimit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float upperSteeringLimit
     * }
     */
    public static final long upperSteeringLimit$offset() {
        return upperSteeringLimit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float upperSteeringLimit
     * }
     */
    public static float upperSteeringLimit(MemorySegment struct) {
        return struct.get(upperSteeringLimit$LAYOUT, upperSteeringLimit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float upperSteeringLimit
     * }
     */
    public static void upperSteeringLimit(MemorySegment struct, float fieldValue) {
        struct.set(upperSteeringLimit$LAYOUT, upperSteeringLimit$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

