// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b3WorldDef {
 *     b3Vec3 gravity;
 *     float restitutionThreshold;
 *     float hitEventThreshold;
 *     float contactHertz;
 *     float contactDampingRatio;
 *     float contactSpeed;
 *     float maximumLinearSpeed;
 *     b3FrictionCallback *frictionCallback;
 *     b3RestitutionCallback *restitutionCallback;
 *     _Bool enableSleep;
 *     _Bool enableContinuous;
 *     uint32_t workerCount;
 *     b3EnqueueTaskCallback *enqueueTask;
 *     b3FinishTaskCallback *finishTask;
 *     void *userTaskContext;
 *     void *userData;
 *     b3CreateDebugShapeCallback *createDebugShape;
 *     b3DestroyDebugShapeCallback *destroyDebugShape;
 *     void *userDebugShapeContext;
 *     b3Capacity capacity;
 *     int internalValue;
 * }
 * }
 */
public class b3WorldDef {

    b3WorldDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b3Vec3.layout().withName("gravity"),
        Box3D.C_FLOAT.withName("restitutionThreshold"),
        Box3D.C_FLOAT.withName("hitEventThreshold"),
        Box3D.C_FLOAT.withName("contactHertz"),
        Box3D.C_FLOAT.withName("contactDampingRatio"),
        Box3D.C_FLOAT.withName("contactSpeed"),
        Box3D.C_FLOAT.withName("maximumLinearSpeed"),
        MemoryLayout.paddingLayout(4),
        Box3D.C_POINTER.withName("frictionCallback"),
        Box3D.C_POINTER.withName("restitutionCallback"),
        Box3D.C_BOOL.withName("enableSleep"),
        Box3D.C_BOOL.withName("enableContinuous"),
        MemoryLayout.paddingLayout(2),
        Box3D.C_INT.withName("workerCount"),
        Box3D.C_POINTER.withName("enqueueTask"),
        Box3D.C_POINTER.withName("finishTask"),
        Box3D.C_POINTER.withName("userTaskContext"),
        Box3D.C_POINTER.withName("userData"),
        Box3D.C_POINTER.withName("createDebugShape"),
        Box3D.C_POINTER.withName("destroyDebugShape"),
        Box3D.C_POINTER.withName("userDebugShapeContext"),
        b3Capacity.layout().withName("capacity"),
        Box3D.C_INT.withName("internalValue")
    ).withName("b3WorldDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout gravity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("gravity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Vec3 gravity
     * }
     */
    public static final GroupLayout gravity$layout() {
        return gravity$LAYOUT;
    }

    private static final long gravity$OFFSET = $LAYOUT.byteOffset(groupElement("gravity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Vec3 gravity
     * }
     */
    public static final long gravity$offset() {
        return gravity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Vec3 gravity
     * }
     */
    public static MemorySegment gravity(MemorySegment struct) {
        return struct.asSlice(gravity$OFFSET, gravity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Vec3 gravity
     * }
     */
    public static void gravity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, gravity$OFFSET, gravity$LAYOUT.byteSize());
    }

    private static final OfFloat restitutionThreshold$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("restitutionThreshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float restitutionThreshold
     * }
     */
    public static final OfFloat restitutionThreshold$layout() {
        return restitutionThreshold$LAYOUT;
    }

    private static final long restitutionThreshold$OFFSET = $LAYOUT.byteOffset(groupElement("restitutionThreshold"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float restitutionThreshold
     * }
     */
    public static final long restitutionThreshold$offset() {
        return restitutionThreshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float restitutionThreshold
     * }
     */
    public static float restitutionThreshold(MemorySegment struct) {
        return struct.get(restitutionThreshold$LAYOUT, restitutionThreshold$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float restitutionThreshold
     * }
     */
    public static void restitutionThreshold(MemorySegment struct, float fieldValue) {
        struct.set(restitutionThreshold$LAYOUT, restitutionThreshold$OFFSET, fieldValue);
    }

    private static final OfFloat hitEventThreshold$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("hitEventThreshold"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float hitEventThreshold
     * }
     */
    public static final OfFloat hitEventThreshold$layout() {
        return hitEventThreshold$LAYOUT;
    }

    private static final long hitEventThreshold$OFFSET = $LAYOUT.byteOffset(groupElement("hitEventThreshold"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float hitEventThreshold
     * }
     */
    public static final long hitEventThreshold$offset() {
        return hitEventThreshold$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hitEventThreshold
     * }
     */
    public static float hitEventThreshold(MemorySegment struct) {
        return struct.get(hitEventThreshold$LAYOUT, hitEventThreshold$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hitEventThreshold
     * }
     */
    public static void hitEventThreshold(MemorySegment struct, float fieldValue) {
        struct.set(hitEventThreshold$LAYOUT, hitEventThreshold$OFFSET, fieldValue);
    }

    private static final OfFloat contactHertz$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("contactHertz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float contactHertz
     * }
     */
    public static final OfFloat contactHertz$layout() {
        return contactHertz$LAYOUT;
    }

    private static final long contactHertz$OFFSET = $LAYOUT.byteOffset(groupElement("contactHertz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float contactHertz
     * }
     */
    public static final long contactHertz$offset() {
        return contactHertz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float contactHertz
     * }
     */
    public static float contactHertz(MemorySegment struct) {
        return struct.get(contactHertz$LAYOUT, contactHertz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float contactHertz
     * }
     */
    public static void contactHertz(MemorySegment struct, float fieldValue) {
        struct.set(contactHertz$LAYOUT, contactHertz$OFFSET, fieldValue);
    }

    private static final OfFloat contactDampingRatio$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("contactDampingRatio"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float contactDampingRatio
     * }
     */
    public static final OfFloat contactDampingRatio$layout() {
        return contactDampingRatio$LAYOUT;
    }

    private static final long contactDampingRatio$OFFSET = $LAYOUT.byteOffset(groupElement("contactDampingRatio"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float contactDampingRatio
     * }
     */
    public static final long contactDampingRatio$offset() {
        return contactDampingRatio$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float contactDampingRatio
     * }
     */
    public static float contactDampingRatio(MemorySegment struct) {
        return struct.get(contactDampingRatio$LAYOUT, contactDampingRatio$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float contactDampingRatio
     * }
     */
    public static void contactDampingRatio(MemorySegment struct, float fieldValue) {
        struct.set(contactDampingRatio$LAYOUT, contactDampingRatio$OFFSET, fieldValue);
    }

    private static final OfFloat contactSpeed$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("contactSpeed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float contactSpeed
     * }
     */
    public static final OfFloat contactSpeed$layout() {
        return contactSpeed$LAYOUT;
    }

    private static final long contactSpeed$OFFSET = $LAYOUT.byteOffset(groupElement("contactSpeed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float contactSpeed
     * }
     */
    public static final long contactSpeed$offset() {
        return contactSpeed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float contactSpeed
     * }
     */
    public static float contactSpeed(MemorySegment struct) {
        return struct.get(contactSpeed$LAYOUT, contactSpeed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float contactSpeed
     * }
     */
    public static void contactSpeed(MemorySegment struct, float fieldValue) {
        struct.set(contactSpeed$LAYOUT, contactSpeed$OFFSET, fieldValue);
    }

    private static final OfFloat maximumLinearSpeed$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maximumLinearSpeed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed
     * }
     */
    public static final OfFloat maximumLinearSpeed$layout() {
        return maximumLinearSpeed$LAYOUT;
    }

    private static final long maximumLinearSpeed$OFFSET = $LAYOUT.byteOffset(groupElement("maximumLinearSpeed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed
     * }
     */
    public static final long maximumLinearSpeed$offset() {
        return maximumLinearSpeed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed
     * }
     */
    public static float maximumLinearSpeed(MemorySegment struct) {
        return struct.get(maximumLinearSpeed$LAYOUT, maximumLinearSpeed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed
     * }
     */
    public static void maximumLinearSpeed(MemorySegment struct, float fieldValue) {
        struct.set(maximumLinearSpeed$LAYOUT, maximumLinearSpeed$OFFSET, fieldValue);
    }

    private static final AddressLayout frictionCallback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("frictionCallback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3FrictionCallback *frictionCallback
     * }
     */
    public static final AddressLayout frictionCallback$layout() {
        return frictionCallback$LAYOUT;
    }

    private static final long frictionCallback$OFFSET = $LAYOUT.byteOffset(groupElement("frictionCallback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3FrictionCallback *frictionCallback
     * }
     */
    public static final long frictionCallback$offset() {
        return frictionCallback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3FrictionCallback *frictionCallback
     * }
     */
    public static MemorySegment frictionCallback(MemorySegment struct) {
        return struct.get(frictionCallback$LAYOUT, frictionCallback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3FrictionCallback *frictionCallback
     * }
     */
    public static void frictionCallback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(frictionCallback$LAYOUT, frictionCallback$OFFSET, fieldValue);
    }

    private static final AddressLayout restitutionCallback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("restitutionCallback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3RestitutionCallback *restitutionCallback
     * }
     */
    public static final AddressLayout restitutionCallback$layout() {
        return restitutionCallback$LAYOUT;
    }

    private static final long restitutionCallback$OFFSET = $LAYOUT.byteOffset(groupElement("restitutionCallback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3RestitutionCallback *restitutionCallback
     * }
     */
    public static final long restitutionCallback$offset() {
        return restitutionCallback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3RestitutionCallback *restitutionCallback
     * }
     */
    public static MemorySegment restitutionCallback(MemorySegment struct) {
        return struct.get(restitutionCallback$LAYOUT, restitutionCallback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3RestitutionCallback *restitutionCallback
     * }
     */
    public static void restitutionCallback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(restitutionCallback$LAYOUT, restitutionCallback$OFFSET, fieldValue);
    }

    private static final OfBoolean enableSleep$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableSleep"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableSleep
     * }
     */
    public static final OfBoolean enableSleep$layout() {
        return enableSleep$LAYOUT;
    }

    private static final long enableSleep$OFFSET = $LAYOUT.byteOffset(groupElement("enableSleep"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableSleep
     * }
     */
    public static final long enableSleep$offset() {
        return enableSleep$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSleep
     * }
     */
    public static boolean enableSleep(MemorySegment struct) {
        return struct.get(enableSleep$LAYOUT, enableSleep$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSleep
     * }
     */
    public static void enableSleep(MemorySegment struct, boolean fieldValue) {
        struct.set(enableSleep$LAYOUT, enableSleep$OFFSET, fieldValue);
    }

    private static final OfBoolean enableContinuous$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enableContinuous"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool enableContinuous
     * }
     */
    public static final OfBoolean enableContinuous$layout() {
        return enableContinuous$LAYOUT;
    }

    private static final long enableContinuous$OFFSET = $LAYOUT.byteOffset(groupElement("enableContinuous"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool enableContinuous
     * }
     */
    public static final long enableContinuous$offset() {
        return enableContinuous$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableContinuous
     * }
     */
    public static boolean enableContinuous(MemorySegment struct) {
        return struct.get(enableContinuous$LAYOUT, enableContinuous$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableContinuous
     * }
     */
    public static void enableContinuous(MemorySegment struct, boolean fieldValue) {
        struct.set(enableContinuous$LAYOUT, enableContinuous$OFFSET, fieldValue);
    }

    private static final OfInt workerCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("workerCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t workerCount
     * }
     */
    public static final OfInt workerCount$layout() {
        return workerCount$LAYOUT;
    }

    private static final long workerCount$OFFSET = $LAYOUT.byteOffset(groupElement("workerCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t workerCount
     * }
     */
    public static final long workerCount$offset() {
        return workerCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t workerCount
     * }
     */
    public static int workerCount(MemorySegment struct) {
        return struct.get(workerCount$LAYOUT, workerCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t workerCount
     * }
     */
    public static void workerCount(MemorySegment struct, int fieldValue) {
        struct.set(workerCount$LAYOUT, workerCount$OFFSET, fieldValue);
    }

    private static final AddressLayout enqueueTask$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("enqueueTask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3EnqueueTaskCallback *enqueueTask
     * }
     */
    public static final AddressLayout enqueueTask$layout() {
        return enqueueTask$LAYOUT;
    }

    private static final long enqueueTask$OFFSET = $LAYOUT.byteOffset(groupElement("enqueueTask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3EnqueueTaskCallback *enqueueTask
     * }
     */
    public static final long enqueueTask$offset() {
        return enqueueTask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3EnqueueTaskCallback *enqueueTask
     * }
     */
    public static MemorySegment enqueueTask(MemorySegment struct) {
        return struct.get(enqueueTask$LAYOUT, enqueueTask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3EnqueueTaskCallback *enqueueTask
     * }
     */
    public static void enqueueTask(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(enqueueTask$LAYOUT, enqueueTask$OFFSET, fieldValue);
    }

    private static final AddressLayout finishTask$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("finishTask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3FinishTaskCallback *finishTask
     * }
     */
    public static final AddressLayout finishTask$layout() {
        return finishTask$LAYOUT;
    }

    private static final long finishTask$OFFSET = $LAYOUT.byteOffset(groupElement("finishTask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3FinishTaskCallback *finishTask
     * }
     */
    public static final long finishTask$offset() {
        return finishTask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3FinishTaskCallback *finishTask
     * }
     */
    public static MemorySegment finishTask(MemorySegment struct) {
        return struct.get(finishTask$LAYOUT, finishTask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3FinishTaskCallback *finishTask
     * }
     */
    public static void finishTask(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(finishTask$LAYOUT, finishTask$OFFSET, fieldValue);
    }

    private static final AddressLayout userTaskContext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userTaskContext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userTaskContext
     * }
     */
    public static final AddressLayout userTaskContext$layout() {
        return userTaskContext$LAYOUT;
    }

    private static final long userTaskContext$OFFSET = $LAYOUT.byteOffset(groupElement("userTaskContext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userTaskContext
     * }
     */
    public static final long userTaskContext$offset() {
        return userTaskContext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userTaskContext
     * }
     */
    public static MemorySegment userTaskContext(MemorySegment struct) {
        return struct.get(userTaskContext$LAYOUT, userTaskContext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userTaskContext
     * }
     */
    public static void userTaskContext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userTaskContext$LAYOUT, userTaskContext$OFFSET, fieldValue);
    }

    private static final AddressLayout userData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static final AddressLayout userData$layout() {
        return userData$LAYOUT;
    }

    private static final long userData$OFFSET = $LAYOUT.byteOffset(groupElement("userData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static final long userData$offset() {
        return userData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static MemorySegment userData(MemorySegment struct) {
        return struct.get(userData$LAYOUT, userData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userData
     * }
     */
    public static void userData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userData$LAYOUT, userData$OFFSET, fieldValue);
    }

    private static final AddressLayout createDebugShape$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("createDebugShape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3CreateDebugShapeCallback *createDebugShape
     * }
     */
    public static final AddressLayout createDebugShape$layout() {
        return createDebugShape$LAYOUT;
    }

    private static final long createDebugShape$OFFSET = $LAYOUT.byteOffset(groupElement("createDebugShape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3CreateDebugShapeCallback *createDebugShape
     * }
     */
    public static final long createDebugShape$offset() {
        return createDebugShape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3CreateDebugShapeCallback *createDebugShape
     * }
     */
    public static MemorySegment createDebugShape(MemorySegment struct) {
        return struct.get(createDebugShape$LAYOUT, createDebugShape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3CreateDebugShapeCallback *createDebugShape
     * }
     */
    public static void createDebugShape(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(createDebugShape$LAYOUT, createDebugShape$OFFSET, fieldValue);
    }

    private static final AddressLayout destroyDebugShape$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("destroyDebugShape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3DestroyDebugShapeCallback *destroyDebugShape
     * }
     */
    public static final AddressLayout destroyDebugShape$layout() {
        return destroyDebugShape$LAYOUT;
    }

    private static final long destroyDebugShape$OFFSET = $LAYOUT.byteOffset(groupElement("destroyDebugShape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3DestroyDebugShapeCallback *destroyDebugShape
     * }
     */
    public static final long destroyDebugShape$offset() {
        return destroyDebugShape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3DestroyDebugShapeCallback *destroyDebugShape
     * }
     */
    public static MemorySegment destroyDebugShape(MemorySegment struct) {
        return struct.get(destroyDebugShape$LAYOUT, destroyDebugShape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3DestroyDebugShapeCallback *destroyDebugShape
     * }
     */
    public static void destroyDebugShape(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(destroyDebugShape$LAYOUT, destroyDebugShape$OFFSET, fieldValue);
    }

    private static final AddressLayout userDebugShapeContext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userDebugShapeContext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userDebugShapeContext
     * }
     */
    public static final AddressLayout userDebugShapeContext$layout() {
        return userDebugShapeContext$LAYOUT;
    }

    private static final long userDebugShapeContext$OFFSET = $LAYOUT.byteOffset(groupElement("userDebugShapeContext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userDebugShapeContext
     * }
     */
    public static final long userDebugShapeContext$offset() {
        return userDebugShapeContext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userDebugShapeContext
     * }
     */
    public static MemorySegment userDebugShapeContext(MemorySegment struct) {
        return struct.get(userDebugShapeContext$LAYOUT, userDebugShapeContext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userDebugShapeContext
     * }
     */
    public static void userDebugShapeContext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userDebugShapeContext$LAYOUT, userDebugShapeContext$OFFSET, fieldValue);
    }

    private static final GroupLayout capacity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b3Capacity capacity
     * }
     */
    public static final GroupLayout capacity$layout() {
        return capacity$LAYOUT;
    }

    private static final long capacity$OFFSET = $LAYOUT.byteOffset(groupElement("capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b3Capacity capacity
     * }
     */
    public static final long capacity$offset() {
        return capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b3Capacity capacity
     * }
     */
    public static MemorySegment capacity(MemorySegment struct) {
        return struct.asSlice(capacity$OFFSET, capacity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b3Capacity capacity
     * }
     */
    public static void capacity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, capacity$OFFSET, capacity$LAYOUT.byteSize());
    }

    private static final OfInt internalValue$LAYOUT = (OfInt)$LAYOUT.select(groupElement("internalValue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static final OfInt internalValue$layout() {
        return internalValue$LAYOUT;
    }

    private static final long internalValue$OFFSET = $LAYOUT.byteOffset(groupElement("internalValue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static final long internalValue$offset() {
        return internalValue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static int internalValue(MemorySegment struct) {
        return struct.get(internalValue$LAYOUT, internalValue$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalValue
     * }
     */
    public static void internalValue(MemorySegment struct, int fieldValue) {
        struct.set(internalValue$LAYOUT, internalValue$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

