// Generated by jextract

package org.box3d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef b3Transform b3WorldTransform
 * }
 */
public class b3WorldTransform extends b3Transform {

    b3WorldTransform() {
        // Should not be called directly
    }
}

